# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.routes.pb import practice_pb2 as app_dot_routes_dot_pb_dot_practice__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in app/routes/pb/practice_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PracticeServiceStub:
    """PracticeService — detached candidate self-serve mock interview. Token-scoped, fully
    candidate-private; NO comp_id / job_id / application_id (practice never reaches the
    funnel). Replaces the former /practice REST surface so ai-agents is all-gRPC.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartPractice = channel.unary_unary(
                '/aiagents.practice.v1.PracticeService/StartPractice',
                request_serializer=app_dot_routes_dot_pb_dot_practice__pb2.StartPracticeRequest.SerializeToString,
                response_deserializer=app_dot_routes_dot_pb_dot_practice__pb2.QuestionResponse.FromString,
                _registered_method=True)
        self.SubmitPracticeTurn = channel.unary_unary(
                '/aiagents.practice.v1.PracticeService/SubmitPracticeTurn',
                request_serializer=app_dot_routes_dot_pb_dot_practice__pb2.SubmitPracticeTurnRequest.SerializeToString,
                response_deserializer=app_dot_routes_dot_pb_dot_practice__pb2.TurnResponse.FromString,
                _registered_method=True)
        self.ListPracticeSessions = channel.unary_unary(
                '/aiagents.practice.v1.PracticeService/ListPracticeSessions',
                request_serializer=app_dot_routes_dot_pb_dot_practice__pb2.ListPracticeSessionsRequest.SerializeToString,
                response_deserializer=app_dot_routes_dot_pb_dot_practice__pb2.PracticeSessionList.FromString,
                _registered_method=True)
        self.GetPracticeFeedback = channel.unary_unary(
                '/aiagents.practice.v1.PracticeService/GetPracticeFeedback',
                request_serializer=app_dot_routes_dot_pb_dot_practice__pb2.GetPracticeFeedbackRequest.SerializeToString,
                response_deserializer=app_dot_routes_dot_pb_dot_practice__pb2.PracticeFeedback.FromString,
                _registered_method=True)


class PracticeServiceServicer:
    """PracticeService — detached candidate self-serve mock interview. Token-scoped, fully
    candidate-private; NO comp_id / job_id / application_id (practice never reaches the
    funnel). Replaces the former /practice REST surface so ai-agents is all-gRPC.
    """

    def StartPractice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitPracticeTurn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPracticeSessions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPracticeFeedback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PracticeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartPractice': grpc.unary_unary_rpc_method_handler(
                    servicer.StartPractice,
                    request_deserializer=app_dot_routes_dot_pb_dot_practice__pb2.StartPracticeRequest.FromString,
                    response_serializer=app_dot_routes_dot_pb_dot_practice__pb2.QuestionResponse.SerializeToString,
            ),
            'SubmitPracticeTurn': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitPracticeTurn,
                    request_deserializer=app_dot_routes_dot_pb_dot_practice__pb2.SubmitPracticeTurnRequest.FromString,
                    response_serializer=app_dot_routes_dot_pb_dot_practice__pb2.TurnResponse.SerializeToString,
            ),
            'ListPracticeSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPracticeSessions,
                    request_deserializer=app_dot_routes_dot_pb_dot_practice__pb2.ListPracticeSessionsRequest.FromString,
                    response_serializer=app_dot_routes_dot_pb_dot_practice__pb2.PracticeSessionList.SerializeToString,
            ),
            'GetPracticeFeedback': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPracticeFeedback,
                    request_deserializer=app_dot_routes_dot_pb_dot_practice__pb2.GetPracticeFeedbackRequest.FromString,
                    response_serializer=app_dot_routes_dot_pb_dot_practice__pb2.PracticeFeedback.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aiagents.practice.v1.PracticeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aiagents.practice.v1.PracticeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PracticeService:
    """PracticeService — detached candidate self-serve mock interview. Token-scoped, fully
    candidate-private; NO comp_id / job_id / application_id (practice never reaches the
    funnel). Replaces the former /practice REST surface so ai-agents is all-gRPC.
    """

    @staticmethod
    def StartPractice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aiagents.practice.v1.PracticeService/StartPractice',
            app_dot_routes_dot_pb_dot_practice__pb2.StartPracticeRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_practice__pb2.QuestionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitPracticeTurn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aiagents.practice.v1.PracticeService/SubmitPracticeTurn',
            app_dot_routes_dot_pb_dot_practice__pb2.SubmitPracticeTurnRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_practice__pb2.TurnResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPracticeSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aiagents.practice.v1.PracticeService/ListPracticeSessions',
            app_dot_routes_dot_pb_dot_practice__pb2.ListPracticeSessionsRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_practice__pb2.PracticeSessionList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPracticeFeedback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aiagents.practice.v1.PracticeService/GetPracticeFeedback',
            app_dot_routes_dot_pb_dot_practice__pb2.GetPracticeFeedbackRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_practice__pb2.PracticeFeedback.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
