# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.routes.pb import analytics_pb2 as app_dot_routes_dot_pb_dot_analytics__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in app/routes/pb/analytics_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AnalyticsServiceStub:
    """AnalyticsService — recruiters see funnel metrics for their company: per-state counts
    and the bottom-of-funnel conversion (hired / total). Comp-scoped, read-only, capped.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetFunnelAnalytics = channel.unary_unary(
                '/admin.analytics.v1.AnalyticsService/GetFunnelAnalytics',
                request_serializer=app_dot_routes_dot_pb_dot_analytics__pb2.FunnelAnalyticsRequest.SerializeToString,
                response_deserializer=app_dot_routes_dot_pb_dot_analytics__pb2.FunnelAnalytics.FromString,
                _registered_method=True)
        self.GetJobScoreDistribution = channel.unary_unary(
                '/admin.analytics.v1.AnalyticsService/GetJobScoreDistribution',
                request_serializer=app_dot_routes_dot_pb_dot_analytics__pb2.JobScoreRequest.SerializeToString,
                response_deserializer=app_dot_routes_dot_pb_dot_analytics__pb2.ScoreDistribution.FromString,
                _registered_method=True)


class AnalyticsServiceServicer:
    """AnalyticsService — recruiters see funnel metrics for their company: per-state counts
    and the bottom-of-funnel conversion (hired / total). Comp-scoped, read-only, capped.
    """

    def GetFunnelAnalytics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJobScoreDistribution(self, request, context):
        """Bias view: the distribution of overall scores across a job's scored candidates.
        v1 reports score-spread stats only (no protected attributes — P1 collects none).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalyticsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetFunnelAnalytics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFunnelAnalytics,
                    request_deserializer=app_dot_routes_dot_pb_dot_analytics__pb2.FunnelAnalyticsRequest.FromString,
                    response_serializer=app_dot_routes_dot_pb_dot_analytics__pb2.FunnelAnalytics.SerializeToString,
            ),
            'GetJobScoreDistribution': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJobScoreDistribution,
                    request_deserializer=app_dot_routes_dot_pb_dot_analytics__pb2.JobScoreRequest.FromString,
                    response_serializer=app_dot_routes_dot_pb_dot_analytics__pb2.ScoreDistribution.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'admin.analytics.v1.AnalyticsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('admin.analytics.v1.AnalyticsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AnalyticsService:
    """AnalyticsService — recruiters see funnel metrics for their company: per-state counts
    and the bottom-of-funnel conversion (hired / total). Comp-scoped, read-only, capped.
    """

    @staticmethod
    def GetFunnelAnalytics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.analytics.v1.AnalyticsService/GetFunnelAnalytics',
            app_dot_routes_dot_pb_dot_analytics__pb2.FunnelAnalyticsRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_analytics__pb2.FunnelAnalytics.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJobScoreDistribution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.analytics.v1.AnalyticsService/GetJobScoreDistribution',
            app_dot_routes_dot_pb_dot_analytics__pb2.JobScoreRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_analytics__pb2.ScoreDistribution.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
