# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.routes.pb import application_pb2 as app_dot_routes_dot_pb_dot_application__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in app/routes/pb/application_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ApplicationServiceStub:
    """ApplicationService — candidate applies to a published job; recruiters list
    applicants for their own jobs. Auth via `authorization` metadata.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Apply = channel.unary_unary(
                '/admin.application.v1.ApplicationService/Apply',
                request_serializer=app_dot_routes_dot_pb_dot_application__pb2.ApplyRequest.SerializeToString,
                response_deserializer=app_dot_routes_dot_pb_dot_application__pb2.ApplicationResponse.FromString,
                _registered_method=True)
        self.ListMyApplications = channel.unary_unary(
                '/admin.application.v1.ApplicationService/ListMyApplications',
                request_serializer=app_dot_routes_dot_pb_dot_application__pb2.ListMyApplicationsRequest.SerializeToString,
                response_deserializer=app_dot_routes_dot_pb_dot_application__pb2.ApplicationList.FromString,
                _registered_method=True)
        self.ListApplicants = channel.unary_unary(
                '/admin.application.v1.ApplicationService/ListApplicants',
                request_serializer=app_dot_routes_dot_pb_dot_application__pb2.ListApplicantsRequest.SerializeToString,
                response_deserializer=app_dot_routes_dot_pb_dot_application__pb2.ApplicationList.FromString,
                _registered_method=True)
        self.WithdrawApplication = channel.unary_unary(
                '/admin.application.v1.ApplicationService/WithdrawApplication',
                request_serializer=app_dot_routes_dot_pb_dot_application__pb2.WithdrawApplicationRequest.SerializeToString,
                response_deserializer=app_dot_routes_dot_pb_dot_application__pb2.ApplicationResponse.FromString,
                _registered_method=True)


class ApplicationServiceServicer:
    """ApplicationService — candidate applies to a published job; recruiters list
    applicants for their own jobs. Auth via `authorization` metadata.
    """

    def Apply(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMyApplications(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListApplicants(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WithdrawApplication(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ApplicationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Apply': grpc.unary_unary_rpc_method_handler(
                    servicer.Apply,
                    request_deserializer=app_dot_routes_dot_pb_dot_application__pb2.ApplyRequest.FromString,
                    response_serializer=app_dot_routes_dot_pb_dot_application__pb2.ApplicationResponse.SerializeToString,
            ),
            'ListMyApplications': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMyApplications,
                    request_deserializer=app_dot_routes_dot_pb_dot_application__pb2.ListMyApplicationsRequest.FromString,
                    response_serializer=app_dot_routes_dot_pb_dot_application__pb2.ApplicationList.SerializeToString,
            ),
            'ListApplicants': grpc.unary_unary_rpc_method_handler(
                    servicer.ListApplicants,
                    request_deserializer=app_dot_routes_dot_pb_dot_application__pb2.ListApplicantsRequest.FromString,
                    response_serializer=app_dot_routes_dot_pb_dot_application__pb2.ApplicationList.SerializeToString,
            ),
            'WithdrawApplication': grpc.unary_unary_rpc_method_handler(
                    servicer.WithdrawApplication,
                    request_deserializer=app_dot_routes_dot_pb_dot_application__pb2.WithdrawApplicationRequest.FromString,
                    response_serializer=app_dot_routes_dot_pb_dot_application__pb2.ApplicationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'admin.application.v1.ApplicationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('admin.application.v1.ApplicationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ApplicationService:
    """ApplicationService — candidate applies to a published job; recruiters list
    applicants for their own jobs. Auth via `authorization` metadata.
    """

    @staticmethod
    def Apply(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.application.v1.ApplicationService/Apply',
            app_dot_routes_dot_pb_dot_application__pb2.ApplyRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_application__pb2.ApplicationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMyApplications(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.application.v1.ApplicationService/ListMyApplications',
            app_dot_routes_dot_pb_dot_application__pb2.ListMyApplicationsRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_application__pb2.ApplicationList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListApplicants(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.application.v1.ApplicationService/ListApplicants',
            app_dot_routes_dot_pb_dot_application__pb2.ListApplicantsRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_application__pb2.ApplicationList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WithdrawApplication(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.application.v1.ApplicationService/WithdrawApplication',
            app_dot_routes_dot_pb_dot_application__pb2.WithdrawApplicationRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_application__pb2.ApplicationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
