# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/routes/pb/application.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 33, 5, "", "app/routes/pb/application.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1f\x61pp/routes/pb/application.proto\x12\x14\x61\x64min.application.v1"/\n\x0c\x41pplyRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63onsent\x18\x02 \x01(\x08"\x1b\n\x19ListMyApplicationsRequest"N\n\x15ListApplicantsRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t"4\n\x1aWithdrawApplicationRequest\x12\x16\n\x0e\x61pplication_id\x18\x01 \x01(\t"g\n\x13\x41pplicationResponse\x12\x16\n\x0e\x61pplication_id\x18\x01 \x01(\t\x12\x0e\n\x06job_id\x18\x02 \x01(\t\x12\x19\n\x11\x63\x61ndidate_user_id\x18\x03 \x01(\t\x12\r\n\x05state\x18\x04 \x01(\t"\x80\x01\n\x0f\x41pplicationList\x12?\n\x0c\x61pplications\x18\x01 \x03(\x0b\x32).admin.application.v1.ApplicationResponse\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\x12\x13\n\x0btotal_count\x18\x03 \x01(\x03\x32\xb4\x03\n\x12\x41pplicationService\x12V\n\x05\x41pply\x12".admin.application.v1.ApplyRequest\x1a).admin.application.v1.ApplicationResponse\x12l\n\x12ListMyApplications\x12/.admin.application.v1.ListMyApplicationsRequest\x1a%.admin.application.v1.ApplicationList\x12\x64\n\x0eListApplicants\x12+.admin.application.v1.ListApplicantsRequest\x1a%.admin.application.v1.ApplicationList\x12r\n\x13WithdrawApplication\x12\x30.admin.application.v1.WithdrawApplicationRequest\x1a).admin.application.v1.ApplicationResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "app.routes.pb.application_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_APPLYREQUEST"]._serialized_start = 57
    _globals["_APPLYREQUEST"]._serialized_end = 104
    _globals["_LISTMYAPPLICATIONSREQUEST"]._serialized_start = 106
    _globals["_LISTMYAPPLICATIONSREQUEST"]._serialized_end = 133
    _globals["_LISTAPPLICANTSREQUEST"]._serialized_start = 135
    _globals["_LISTAPPLICANTSREQUEST"]._serialized_end = 213
    _globals["_WITHDRAWAPPLICATIONREQUEST"]._serialized_start = 215
    _globals["_WITHDRAWAPPLICATIONREQUEST"]._serialized_end = 267
    _globals["_APPLICATIONRESPONSE"]._serialized_start = 269
    _globals["_APPLICATIONRESPONSE"]._serialized_end = 372
    _globals["_APPLICATIONLIST"]._serialized_start = 375
    _globals["_APPLICATIONLIST"]._serialized_end = 503
    _globals["_APPLICATIONSERVICE"]._serialized_start = 506
    _globals["_APPLICATIONSERVICE"]._serialized_end = 942
# @@protoc_insertion_point(module_scope)
