# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.routes.pb import aptitude_pb2 as app_dot_pb_dot_aptitude__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in app/pb/aptitude_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AptitudeServiceStub:
    """AptitudeService — the candidate fetches the test (questions only, no answer key) and
    submits answers; grading emits aptitude.graded to drive the funnel gate. Candidate-only,
    scoped to the caller's own application.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAptitudeTest = channel.unary_unary(
                '/admin.aptitude.v1.AptitudeService/GetAptitudeTest',
                request_serializer=app_dot_pb_dot_aptitude__pb2.GetTestRequest.SerializeToString,
                response_deserializer=app_dot_pb_dot_aptitude__pb2.AptitudeTest.FromString,
                _registered_method=True)
        self.SubmitAptitude = channel.unary_unary(
                '/admin.aptitude.v1.AptitudeService/SubmitAptitude',
                request_serializer=app_dot_pb_dot_aptitude__pb2.SubmitRequest.SerializeToString,
                response_deserializer=app_dot_pb_dot_aptitude__pb2.AptitudeResult.FromString,
                _registered_method=True)


class AptitudeServiceServicer:
    """AptitudeService — the candidate fetches the test (questions only, no answer key) and
    submits answers; grading emits aptitude.graded to drive the funnel gate. Candidate-only,
    scoped to the caller's own application.
    """

    def GetAptitudeTest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitAptitude(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AptitudeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAptitudeTest': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAptitudeTest,
                    request_deserializer=app_dot_pb_dot_aptitude__pb2.GetTestRequest.FromString,
                    response_serializer=app_dot_pb_dot_aptitude__pb2.AptitudeTest.SerializeToString,
            ),
            'SubmitAptitude': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitAptitude,
                    request_deserializer=app_dot_pb_dot_aptitude__pb2.SubmitRequest.FromString,
                    response_serializer=app_dot_pb_dot_aptitude__pb2.AptitudeResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'admin.aptitude.v1.AptitudeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('admin.aptitude.v1.AptitudeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AptitudeService:
    """AptitudeService — the candidate fetches the test (questions only, no answer key) and
    submits answers; grading emits aptitude.graded to drive the funnel gate. Candidate-only,
    scoped to the caller's own application.
    """

    @staticmethod
    def GetAptitudeTest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.aptitude.v1.AptitudeService/GetAptitudeTest',
            app_dot_pb_dot_aptitude__pb2.GetTestRequest.SerializeToString,
            app_dot_pb_dot_aptitude__pb2.AptitudeTest.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitAptitude(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.aptitude.v1.AptitudeService/SubmitAptitude',
            app_dot_pb_dot_aptitude__pb2.SubmitRequest.SerializeToString,
            app_dot_pb_dot_aptitude__pb2.AptitudeResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
