# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.routes.pb import auth_pb2 as app_dot_pb_dot_auth__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in app/pb/auth_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuthServiceStub:
    """AuthService — identity + session for company users and candidates.
    Routes are thin: each RPC just calls an app/resources function.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterCompany = channel.unary_unary(
                '/admin.auth.v1.AuthService/RegisterCompany',
                request_serializer=app_dot_pb_dot_auth__pb2.RegisterCompanyRequest.SerializeToString,
                response_deserializer=app_dot_pb_dot_auth__pb2.UserResponse.FromString,
                _registered_method=True)
        self.RegisterCandidate = channel.unary_unary(
                '/admin.auth.v1.AuthService/RegisterCandidate',
                request_serializer=app_dot_pb_dot_auth__pb2.RegisterCandidateRequest.SerializeToString,
                response_deserializer=app_dot_pb_dot_auth__pb2.UserResponse.FromString,
                _registered_method=True)
        self.Verify = channel.unary_unary(
                '/admin.auth.v1.AuthService/Verify',
                request_serializer=app_dot_pb_dot_auth__pb2.VerifyRequest.SerializeToString,
                response_deserializer=app_dot_pb_dot_auth__pb2.UserResponse.FromString,
                _registered_method=True)
        self.Login = channel.unary_unary(
                '/admin.auth.v1.AuthService/Login',
                request_serializer=app_dot_pb_dot_auth__pb2.LoginRequest.SerializeToString,
                response_deserializer=app_dot_pb_dot_auth__pb2.TokenResponse.FromString,
                _registered_method=True)
        self.Refresh = channel.unary_unary(
                '/admin.auth.v1.AuthService/Refresh',
                request_serializer=app_dot_pb_dot_auth__pb2.RefreshRequest.SerializeToString,
                response_deserializer=app_dot_pb_dot_auth__pb2.TokenResponse.FromString,
                _registered_method=True)
        self.Logout = channel.unary_unary(
                '/admin.auth.v1.AuthService/Logout',
                request_serializer=app_dot_pb_dot_auth__pb2.LogoutRequest.SerializeToString,
                response_deserializer=app_dot_pb_dot_auth__pb2.LogoutResponse.FromString,
                _registered_method=True)
        self.InviteRecruiter = channel.unary_unary(
                '/admin.auth.v1.AuthService/InviteRecruiter',
                request_serializer=app_dot_pb_dot_auth__pb2.InviteRecruiterRequest.SerializeToString,
                response_deserializer=app_dot_pb_dot_auth__pb2.UserResponse.FromString,
                _registered_method=True)
        self.ForgotPassword = channel.unary_unary(
                '/admin.auth.v1.AuthService/ForgotPassword',
                request_serializer=app_dot_pb_dot_auth__pb2.ForgotPasswordRequest.SerializeToString,
                response_deserializer=app_dot_pb_dot_auth__pb2.OkResponse.FromString,
                _registered_method=True)
        self.ResetPassword = channel.unary_unary(
                '/admin.auth.v1.AuthService/ResetPassword',
                request_serializer=app_dot_pb_dot_auth__pb2.ResetPasswordRequest.SerializeToString,
                response_deserializer=app_dot_pb_dot_auth__pb2.OkResponse.FromString,
                _registered_method=True)
        self.Me = channel.unary_unary(
                '/admin.auth.v1.AuthService/Me',
                request_serializer=app_dot_pb_dot_auth__pb2.MeRequest.SerializeToString,
                response_deserializer=app_dot_pb_dot_auth__pb2.IdentityResponse.FromString,
                _registered_method=True)


class AuthServiceServicer:
    """AuthService — identity + session for company users and candidates.
    Routes are thin: each RPC just calls an app/resources function.
    """

    def RegisterCompany(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterCandidate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Verify(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Refresh(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InviteRecruiter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ForgotPassword(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetPassword(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Me(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterCompany': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterCompany,
                    request_deserializer=app_dot_pb_dot_auth__pb2.RegisterCompanyRequest.FromString,
                    response_serializer=app_dot_pb_dot_auth__pb2.UserResponse.SerializeToString,
            ),
            'RegisterCandidate': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterCandidate,
                    request_deserializer=app_dot_pb_dot_auth__pb2.RegisterCandidateRequest.FromString,
                    response_serializer=app_dot_pb_dot_auth__pb2.UserResponse.SerializeToString,
            ),
            'Verify': grpc.unary_unary_rpc_method_handler(
                    servicer.Verify,
                    request_deserializer=app_dot_pb_dot_auth__pb2.VerifyRequest.FromString,
                    response_serializer=app_dot_pb_dot_auth__pb2.UserResponse.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=app_dot_pb_dot_auth__pb2.LoginRequest.FromString,
                    response_serializer=app_dot_pb_dot_auth__pb2.TokenResponse.SerializeToString,
            ),
            'Refresh': grpc.unary_unary_rpc_method_handler(
                    servicer.Refresh,
                    request_deserializer=app_dot_pb_dot_auth__pb2.RefreshRequest.FromString,
                    response_serializer=app_dot_pb_dot_auth__pb2.TokenResponse.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=app_dot_pb_dot_auth__pb2.LogoutRequest.FromString,
                    response_serializer=app_dot_pb_dot_auth__pb2.LogoutResponse.SerializeToString,
            ),
            'InviteRecruiter': grpc.unary_unary_rpc_method_handler(
                    servicer.InviteRecruiter,
                    request_deserializer=app_dot_pb_dot_auth__pb2.InviteRecruiterRequest.FromString,
                    response_serializer=app_dot_pb_dot_auth__pb2.UserResponse.SerializeToString,
            ),
            'ForgotPassword': grpc.unary_unary_rpc_method_handler(
                    servicer.ForgotPassword,
                    request_deserializer=app_dot_pb_dot_auth__pb2.ForgotPasswordRequest.FromString,
                    response_serializer=app_dot_pb_dot_auth__pb2.OkResponse.SerializeToString,
            ),
            'ResetPassword': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetPassword,
                    request_deserializer=app_dot_pb_dot_auth__pb2.ResetPasswordRequest.FromString,
                    response_serializer=app_dot_pb_dot_auth__pb2.OkResponse.SerializeToString,
            ),
            'Me': grpc.unary_unary_rpc_method_handler(
                    servicer.Me,
                    request_deserializer=app_dot_pb_dot_auth__pb2.MeRequest.FromString,
                    response_serializer=app_dot_pb_dot_auth__pb2.IdentityResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'admin.auth.v1.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('admin.auth.v1.AuthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthService:
    """AuthService — identity + session for company users and candidates.
    Routes are thin: each RPC just calls an app/resources function.
    """

    @staticmethod
    def RegisterCompany(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.auth.v1.AuthService/RegisterCompany',
            app_dot_pb_dot_auth__pb2.RegisterCompanyRequest.SerializeToString,
            app_dot_pb_dot_auth__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterCandidate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.auth.v1.AuthService/RegisterCandidate',
            app_dot_pb_dot_auth__pb2.RegisterCandidateRequest.SerializeToString,
            app_dot_pb_dot_auth__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Verify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.auth.v1.AuthService/Verify',
            app_dot_pb_dot_auth__pb2.VerifyRequest.SerializeToString,
            app_dot_pb_dot_auth__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.auth.v1.AuthService/Login',
            app_dot_pb_dot_auth__pb2.LoginRequest.SerializeToString,
            app_dot_pb_dot_auth__pb2.TokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Refresh(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.auth.v1.AuthService/Refresh',
            app_dot_pb_dot_auth__pb2.RefreshRequest.SerializeToString,
            app_dot_pb_dot_auth__pb2.TokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.auth.v1.AuthService/Logout',
            app_dot_pb_dot_auth__pb2.LogoutRequest.SerializeToString,
            app_dot_pb_dot_auth__pb2.LogoutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InviteRecruiter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.auth.v1.AuthService/InviteRecruiter',
            app_dot_pb_dot_auth__pb2.InviteRecruiterRequest.SerializeToString,
            app_dot_pb_dot_auth__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ForgotPassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.auth.v1.AuthService/ForgotPassword',
            app_dot_pb_dot_auth__pb2.ForgotPasswordRequest.SerializeToString,
            app_dot_pb_dot_auth__pb2.OkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetPassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.auth.v1.AuthService/ResetPassword',
            app_dot_pb_dot_auth__pb2.ResetPasswordRequest.SerializeToString,
            app_dot_pb_dot_auth__pb2.OkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Me(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.auth.v1.AuthService/Me',
            app_dot_pb_dot_auth__pb2.MeRequest.SerializeToString,
            app_dot_pb_dot_auth__pb2.IdentityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
