# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.routes.pb import coding_pb2 as app_dot_routes_dot_pb_dot_coding__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in app/routes/pb/coding_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CodingServiceStub:
    """CodingService — candidate runs + submits assessment code. Execution is server-side
    (resource-capped subprocess). Candidate-owned via the application; hidden test cases
    and typed answer keys never cross the wire.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCodingTask = channel.unary_unary(
                '/admin.coding.v1.CodingService/GetCodingTask',
                request_serializer=app_dot_routes_dot_pb_dot_coding__pb2.GetCodingTaskRequest.SerializeToString,
                response_deserializer=app_dot_routes_dot_pb_dot_coding__pb2.CodingTask.FromString,
                _registered_method=True)
        self.RunCode = channel.unary_unary(
                '/admin.coding.v1.CodingService/RunCode',
                request_serializer=app_dot_routes_dot_pb_dot_coding__pb2.RunCodeRequest.SerializeToString,
                response_deserializer=app_dot_routes_dot_pb_dot_coding__pb2.RunResult.FromString,
                _registered_method=True)
        self.SubmitCoding = channel.unary_unary(
                '/admin.coding.v1.CodingService/SubmitCoding',
                request_serializer=app_dot_routes_dot_pb_dot_coding__pb2.SubmitCodingRequest.SerializeToString,
                response_deserializer=app_dot_routes_dot_pb_dot_coding__pb2.SubmitResult.FromString,
                _registered_method=True)


class CodingServiceServicer:
    """CodingService — candidate runs + submits assessment code. Execution is server-side
    (resource-capped subprocess). Candidate-owned via the application; hidden test cases
    and typed answer keys never cross the wire.
    """

    def GetCodingTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunCode(self, request, context):
        """ephemeral, no grade
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitCoding(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CodingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCodingTask': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCodingTask,
                    request_deserializer=app_dot_routes_dot_pb_dot_coding__pb2.GetCodingTaskRequest.FromString,
                    response_serializer=app_dot_routes_dot_pb_dot_coding__pb2.CodingTask.SerializeToString,
            ),
            'RunCode': grpc.unary_unary_rpc_method_handler(
                    servicer.RunCode,
                    request_deserializer=app_dot_routes_dot_pb_dot_coding__pb2.RunCodeRequest.FromString,
                    response_serializer=app_dot_routes_dot_pb_dot_coding__pb2.RunResult.SerializeToString,
            ),
            'SubmitCoding': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitCoding,
                    request_deserializer=app_dot_routes_dot_pb_dot_coding__pb2.SubmitCodingRequest.FromString,
                    response_serializer=app_dot_routes_dot_pb_dot_coding__pb2.SubmitResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'admin.coding.v1.CodingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('admin.coding.v1.CodingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CodingService:
    """CodingService — candidate runs + submits assessment code. Execution is server-side
    (resource-capped subprocess). Candidate-owned via the application; hidden test cases
    and typed answer keys never cross the wire.
    """

    @staticmethod
    def GetCodingTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.coding.v1.CodingService/GetCodingTask',
            app_dot_routes_dot_pb_dot_coding__pb2.GetCodingTaskRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_coding__pb2.CodingTask.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.coding.v1.CodingService/RunCode',
            app_dot_routes_dot_pb_dot_coding__pb2.RunCodeRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_coding__pb2.RunResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitCoding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.coding.v1.CodingService/SubmitCoding',
            app_dot_routes_dot_pb_dot_coding__pb2.SubmitCodingRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_coding__pb2.SubmitResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
