# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.routes.pb import company_profile_pb2 as app_dot_routes_dot_pb_dot_company__profile__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in app/routes/pb/company_profile_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CompanyProfileServiceStub:
    """CompanyProfileService — public read of an employer's branding + trust signals.
    GetCompanyProfile is an UNAUTHENTICATED read of a published company (the public REST
    mirror shares the resource). Upsert/logo-presign (company-branding) are out of scope.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCompanyProfile = channel.unary_unary(
                '/admin.company_profile.v1.CompanyProfileService/GetCompanyProfile',
                request_serializer=app_dot_routes_dot_pb_dot_company__profile__pb2.GetCompanyProfileRequest.SerializeToString,
                response_deserializer=app_dot_routes_dot_pb_dot_company__profile__pb2.CompanyProfile.FromString,
                _registered_method=True)


class CompanyProfileServiceServicer:
    """CompanyProfileService — public read of an employer's branding + trust signals.
    GetCompanyProfile is an UNAUTHENTICATED read of a published company (the public REST
    mirror shares the resource). Upsert/logo-presign (company-branding) are out of scope.
    """

    def GetCompanyProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CompanyProfileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCompanyProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCompanyProfile,
                    request_deserializer=app_dot_routes_dot_pb_dot_company__profile__pb2.GetCompanyProfileRequest.FromString,
                    response_serializer=app_dot_routes_dot_pb_dot_company__profile__pb2.CompanyProfile.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'admin.company_profile.v1.CompanyProfileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('admin.company_profile.v1.CompanyProfileService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CompanyProfileService:
    """CompanyProfileService — public read of an employer's branding + trust signals.
    GetCompanyProfile is an UNAUTHENTICATED read of a published company (the public REST
    mirror shares the resource). Upsert/logo-presign (company-branding) are out of scope.
    """

    @staticmethod
    def GetCompanyProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.company_profile.v1.CompanyProfileService/GetCompanyProfile',
            app_dot_routes_dot_pb_dot_company__profile__pb2.GetCompanyProfileRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_company__profile__pb2.CompanyProfile.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
