# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/routes/pb/discovery.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'app/routes/pb/discovery.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x61pp/routes/pb/discovery.proto\x12\x12\x61\x64min.discovery.v1\"\x9c\x01\n\x11SearchJobsRequest\x12\t\n\x01q\x18\x01 \x01(\t\x12\x10\n\x08location\x18\x02 \x01(\t\x12\x0e\n\x06remote\x18\x03 \x01(\t\x12\x0c\n\x04type\x18\x04 \x01(\t\x12\r\n\x05level\x18\x05 \x01(\t\x12\x0e\n\x06skills\x18\x06 \x03(\t\x12\x0c\n\x04sort\x18\x07 \x01(\t\x12\x0c\n\x04page\x18\x08 \x01(\x05\x12\x11\n\tpage_size\x18\t \x01(\x05\"\x87\x02\n\x07JobCard\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x14\n\x0c\x63ompany_name\x18\x03 \x01(\t\x12\x12\n\ncompany_id\x18\x04 \x01(\t\x12\x10\n\x08location\x18\x05 \x01(\t\x12\x13\n\x0bremote_mode\x18\x06 \x01(\t\x12\x17\n\x0f\x65mployment_type\x18\x07 \x01(\t\x12\x12\n\nsalary_min\x18\x08 \x01(\x05\x12\x12\n\nsalary_max\x18\t \x01(\x05\x12\x17\n\x0fsalary_currency\x18\n \x01(\t\x12\x0e\n\x06skills\x18\x0b \x03(\t\x12\x11\n\tposted_at\x18\x0c \x01(\t\x12\x0f\n\x07snippet\x18\r \x01(\t\"+\n\x0b\x46\x61\x63\x65tBucket\x12\r\n\x05value\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\"\xb3\x01\n\x06\x46\x61\x63\x65ts\x12\x34\n\x0bremote_mode\x18\x01 \x03(\x0b\x32\x1f.admin.discovery.v1.FacetBucket\x12\x38\n\x0f\x65mployment_type\x18\x02 \x03(\x0b\x32\x1f.admin.discovery.v1.FacetBucket\x12\x39\n\x10\x65xperience_level\x18\x03 \x03(\x0b\x32\x1f.admin.discovery.v1.FacetBucket\"\x9b\x01\n\x12SearchJobsResponse\x12)\n\x04jobs\x18\x01 \x03(\x0b\x32\x1b.admin.discovery.v1.JobCard\x12*\n\x06\x66\x61\x63\x65ts\x18\x02 \x01(\x0b\x32\x1a.admin.discovery.v1.Facets\x12\r\n\x05total\x18\x03 \x01(\x05\x12\x0c\n\x04page\x18\x04 \x01(\x05\x12\x11\n\tpage_size\x18\x05 \x01(\x05\x32o\n\x10\x44iscoveryService\x12[\n\nSearchJobs\x12%.admin.discovery.v1.SearchJobsRequest\x1a&.admin.discovery.v1.SearchJobsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.routes.pb.discovery_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SEARCHJOBSREQUEST']._serialized_start=54
  _globals['_SEARCHJOBSREQUEST']._serialized_end=210
  _globals['_JOBCARD']._serialized_start=213
  _globals['_JOBCARD']._serialized_end=476
  _globals['_FACETBUCKET']._serialized_start=478
  _globals['_FACETBUCKET']._serialized_end=521
  _globals['_FACETS']._serialized_start=524
  _globals['_FACETS']._serialized_end=703
  _globals['_SEARCHJOBSRESPONSE']._serialized_start=706
  _globals['_SEARCHJOBSRESPONSE']._serialized_end=861
  _globals['_DISCOVERYSERVICE']._serialized_start=863
  _globals['_DISCOVERYSERVICE']._serialized_end=974
# @@protoc_insertion_point(module_scope)
