# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.routes.pb import discovery_pb2 as app_dot_routes_dot_pb_dot_discovery__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in app/routes/pb/discovery_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DiscoveryServiceStub:
    """DiscoveryService — the candidate-facing job marketplace (search + browse the published
    catalog with filters + facets). The authed gRPC SearchJobs and the public REST
    GET /public/jobs (SSR/SEO surface) share one resources/discovery.py over the `jobs`
    collection (Mongo $text + $facet); only published jobs are ever returned, and the DTO
    is scrubbed of company/job internals.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SearchJobs = channel.unary_unary(
                '/admin.discovery.v1.DiscoveryService/SearchJobs',
                request_serializer=app_dot_routes_dot_pb_dot_discovery__pb2.SearchJobsRequest.SerializeToString,
                response_deserializer=app_dot_routes_dot_pb_dot_discovery__pb2.SearchJobsResponse.FromString,
                _registered_method=True)


class DiscoveryServiceServicer:
    """DiscoveryService — the candidate-facing job marketplace (search + browse the published
    catalog with filters + facets). The authed gRPC SearchJobs and the public REST
    GET /public/jobs (SSR/SEO surface) share one resources/discovery.py over the `jobs`
    collection (Mongo $text + $facet); only published jobs are ever returned, and the DTO
    is scrubbed of company/job internals.
    """

    def SearchJobs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DiscoveryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SearchJobs': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchJobs,
                    request_deserializer=app_dot_routes_dot_pb_dot_discovery__pb2.SearchJobsRequest.FromString,
                    response_serializer=app_dot_routes_dot_pb_dot_discovery__pb2.SearchJobsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'admin.discovery.v1.DiscoveryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('admin.discovery.v1.DiscoveryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DiscoveryService:
    """DiscoveryService — the candidate-facing job marketplace (search + browse the published
    catalog with filters + facets). The authed gRPC SearchJobs and the public REST
    GET /public/jobs (SSR/SEO surface) share one resources/discovery.py over the `jobs`
    collection (Mongo $text + $facet); only published jobs are ever returned, and the DTO
    is scrubbed of company/job internals.
    """

    @staticmethod
    def SearchJobs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.discovery.v1.DiscoveryService/SearchJobs',
            app_dot_routes_dot_pb_dot_discovery__pb2.SearchJobsRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_discovery__pb2.SearchJobsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
