# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/routes/pb/job_alerts.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'app/routes/pb/job_alerts.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x61pp/routes/pb/job_alerts.proto\x12\x13\x61\x64min.job_alerts.v1\"x\n\x0c\x41lertFilters\x12\x10\n\x08location\x18\x01 \x01(\t\x12\x13\n\x0bremote_mode\x18\x02 \x01(\t\x12\x17\n\x0f\x65mployment_type\x18\x03 \x01(\t\x12\x18\n\x10\x65xperience_level\x18\x04 \x01(\t\x12\x0e\n\x06skills\x18\x05 \x03(\t\"l\n\x12\x43reateAlertRequest\x12\x0f\n\x07keyword\x18\x01 \x01(\t\x12\x32\n\x07\x66ilters\x18\x02 \x01(\x0b\x32!.admin.job_alerts.v1.AlertFilters\x12\x11\n\tfrequency\x18\x03 \x01(\t\"\x9d\x01\n\x08JobAlert\x12\x10\n\x08\x61lert_id\x18\x01 \x01(\t\x12\x0f\n\x07keyword\x18\x02 \x01(\t\x12\x32\n\x07\x66ilters\x18\x03 \x01(\x0b\x32!.admin.job_alerts.v1.AlertFilters\x12\x11\n\tfrequency\x18\x04 \x01(\t\x12\x12\n\ncreated_at\x18\x05 \x01(\t\x12\x13\n\x0blast_run_at\x18\x06 \x01(\t\"\x13\n\x11ListAlertsRequest\"C\n\x12ListAlertsResponse\x12-\n\x06\x61lerts\x18\x01 \x03(\x0b\x32\x1d.admin.job_alerts.v1.JobAlert\"&\n\x12\x44\x65leteAlertRequest\x12\x10\n\x08\x61lert_id\x18\x01 \x01(\t\"&\n\x13\x44\x65leteAlertResponse\x12\x0f\n\x07\x64\x65leted\x18\x01 \x01(\x08\x32\xaa\x02\n\x10JobAlertsService\x12U\n\x0b\x43reateAlert\x12\'.admin.job_alerts.v1.CreateAlertRequest\x1a\x1d.admin.job_alerts.v1.JobAlert\x12]\n\nListAlerts\x12&.admin.job_alerts.v1.ListAlertsRequest\x1a\'.admin.job_alerts.v1.ListAlertsResponse\x12`\n\x0b\x44\x65leteAlert\x12\'.admin.job_alerts.v1.DeleteAlertRequest\x1a(.admin.job_alerts.v1.DeleteAlertResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.routes.pb.job_alerts_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ALERTFILTERS']._serialized_start=55
  _globals['_ALERTFILTERS']._serialized_end=175
  _globals['_CREATEALERTREQUEST']._serialized_start=177
  _globals['_CREATEALERTREQUEST']._serialized_end=285
  _globals['_JOBALERT']._serialized_start=288
  _globals['_JOBALERT']._serialized_end=445
  _globals['_LISTALERTSREQUEST']._serialized_start=447
  _globals['_LISTALERTSREQUEST']._serialized_end=466
  _globals['_LISTALERTSRESPONSE']._serialized_start=468
  _globals['_LISTALERTSRESPONSE']._serialized_end=535
  _globals['_DELETEALERTREQUEST']._serialized_start=537
  _globals['_DELETEALERTREQUEST']._serialized_end=575
  _globals['_DELETEALERTRESPONSE']._serialized_start=577
  _globals['_DELETEALERTRESPONSE']._serialized_end=615
  _globals['_JOBALERTSSERVICE']._serialized_start=618
  _globals['_JOBALERTSSERVICE']._serialized_end=916
# @@protoc_insertion_point(module_scope)
