# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.routes.pb import job_alerts_pb2 as app_dot_routes_dot_pb_dot_job__alerts__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in app/routes/pb/job_alerts_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class JobAlertsServiceStub:
    """JobAlertsService — a candidate's saved searches. Owner is derived from the bearer
    token (caller_identity); candidate_user_id is NEVER a request field. Running the
    searches + emitting notifications is a SCHEDULED BACKEND SWEEP, not this request path.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateAlert = channel.unary_unary(
                '/admin.job_alerts.v1.JobAlertsService/CreateAlert',
                request_serializer=app_dot_routes_dot_pb_dot_job__alerts__pb2.CreateAlertRequest.SerializeToString,
                response_deserializer=app_dot_routes_dot_pb_dot_job__alerts__pb2.JobAlert.FromString,
                _registered_method=True)
        self.ListAlerts = channel.unary_unary(
                '/admin.job_alerts.v1.JobAlertsService/ListAlerts',
                request_serializer=app_dot_routes_dot_pb_dot_job__alerts__pb2.ListAlertsRequest.SerializeToString,
                response_deserializer=app_dot_routes_dot_pb_dot_job__alerts__pb2.ListAlertsResponse.FromString,
                _registered_method=True)
        self.DeleteAlert = channel.unary_unary(
                '/admin.job_alerts.v1.JobAlertsService/DeleteAlert',
                request_serializer=app_dot_routes_dot_pb_dot_job__alerts__pb2.DeleteAlertRequest.SerializeToString,
                response_deserializer=app_dot_routes_dot_pb_dot_job__alerts__pb2.DeleteAlertResponse.FromString,
                _registered_method=True)


class JobAlertsServiceServicer:
    """JobAlertsService — a candidate's saved searches. Owner is derived from the bearer
    token (caller_identity); candidate_user_id is NEVER a request field. Running the
    searches + emitting notifications is a SCHEDULED BACKEND SWEEP, not this request path.
    """

    def CreateAlert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAlerts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAlert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JobAlertsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateAlert': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAlert,
                    request_deserializer=app_dot_routes_dot_pb_dot_job__alerts__pb2.CreateAlertRequest.FromString,
                    response_serializer=app_dot_routes_dot_pb_dot_job__alerts__pb2.JobAlert.SerializeToString,
            ),
            'ListAlerts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAlerts,
                    request_deserializer=app_dot_routes_dot_pb_dot_job__alerts__pb2.ListAlertsRequest.FromString,
                    response_serializer=app_dot_routes_dot_pb_dot_job__alerts__pb2.ListAlertsResponse.SerializeToString,
            ),
            'DeleteAlert': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAlert,
                    request_deserializer=app_dot_routes_dot_pb_dot_job__alerts__pb2.DeleteAlertRequest.FromString,
                    response_serializer=app_dot_routes_dot_pb_dot_job__alerts__pb2.DeleteAlertResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'admin.job_alerts.v1.JobAlertsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('admin.job_alerts.v1.JobAlertsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class JobAlertsService:
    """JobAlertsService — a candidate's saved searches. Owner is derived from the bearer
    token (caller_identity); candidate_user_id is NEVER a request field. Running the
    searches + emitting notifications is a SCHEDULED BACKEND SWEEP, not this request path.
    """

    @staticmethod
    def CreateAlert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.job_alerts.v1.JobAlertsService/CreateAlert',
            app_dot_routes_dot_pb_dot_job__alerts__pb2.CreateAlertRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_job__alerts__pb2.JobAlert.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAlerts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.job_alerts.v1.JobAlertsService/ListAlerts',
            app_dot_routes_dot_pb_dot_job__alerts__pb2.ListAlertsRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_job__alerts__pb2.ListAlertsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteAlert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.job_alerts.v1.JobAlertsService/DeleteAlert',
            app_dot_routes_dot_pb_dot_job__alerts__pb2.DeleteAlertRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_job__alerts__pb2.DeleteAlertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
