# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/routes/pb/job.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'app/routes/pb/job.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x61pp/routes/pb/job.proto\x12\x0c\x61\x64min.job.v1\";\n\tPublicJob\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07jd_text\x18\x03 \x01(\t\"2\n\x10\x43reateJobRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0f\n\x07jd_text\x18\x02 \x01(\t\"\x1f\n\rGetJobRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\"#\n\x11PublishJobRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\"\x11\n\x0fListJobsRequest\"M\n\x0bJobResponse\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63omp_id\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\";\n\x10ListJobsResponse\x12\'\n\x04jobs\x18\x01 \x03(\x0b\x32\x19.admin.job.v1.JobResponse2\xf1\x02\n\nJobService\x12\x46\n\tCreateJob\x12\x1e.admin.job.v1.CreateJobRequest\x1a\x19.admin.job.v1.JobResponse\x12@\n\x06GetJob\x12\x1b.admin.job.v1.GetJobRequest\x1a\x19.admin.job.v1.JobResponse\x12I\n\x08ListJobs\x12\x1d.admin.job.v1.ListJobsRequest\x1a\x1e.admin.job.v1.ListJobsResponse\x12H\n\nPublishJob\x12\x1f.admin.job.v1.PublishJobRequest\x1a\x19.admin.job.v1.JobResponse\x12\x44\n\x0cGetPublicJob\x12\x1b.admin.job.v1.GetJobRequest\x1a\x17.admin.job.v1.PublicJobb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.routes.pb.job_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PUBLICJOB']._serialized_start=41
  _globals['_PUBLICJOB']._serialized_end=100
  _globals['_CREATEJOBREQUEST']._serialized_start=102
  _globals['_CREATEJOBREQUEST']._serialized_end=152
  _globals['_GETJOBREQUEST']._serialized_start=154
  _globals['_GETJOBREQUEST']._serialized_end=185
  _globals['_PUBLISHJOBREQUEST']._serialized_start=187
  _globals['_PUBLISHJOBREQUEST']._serialized_end=222
  _globals['_LISTJOBSREQUEST']._serialized_start=224
  _globals['_LISTJOBSREQUEST']._serialized_end=241
  _globals['_JOBRESPONSE']._serialized_start=243
  _globals['_JOBRESPONSE']._serialized_end=320
  _globals['_LISTJOBSRESPONSE']._serialized_start=322
  _globals['_LISTJOBSRESPONSE']._serialized_end=381
  _globals['_JOBSERVICE']._serialized_start=384
  _globals['_JOBSERVICE']._serialized_end=753
# @@protoc_insertion_point(module_scope)
