# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

from app.routes.pb import messaging_pb2 as app_dot_routes_dot_pb_dot_messaging__pb2

GRPC_GENERATED_VERSION = "1.81.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in app/routes/pb/messaging_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class MessagingServiceStub:
    """MessagingService — candidate <-> recruiter chat, 1:1 with an application. Authed;
    sender identity from the token (no impersonation); authz reuses the application owner.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendMessage = channel.unary_unary(
            "/admin.messaging.v1.MessagingService/SendMessage",
            request_serializer=app_dot_routes_dot_pb_dot_messaging__pb2.SendMessageRequest.SerializeToString,
            response_deserializer=app_dot_routes_dot_pb_dot_messaging__pb2.MessageDTO.FromString,
            _registered_method=True,
        )
        self.ListThreads = channel.unary_unary(
            "/admin.messaging.v1.MessagingService/ListThreads",
            request_serializer=app_dot_routes_dot_pb_dot_messaging__pb2.ListThreadsRequest.SerializeToString,
            response_deserializer=app_dot_routes_dot_pb_dot_messaging__pb2.ListThreadsResponse.FromString,
            _registered_method=True,
        )
        self.ListMessages = channel.unary_unary(
            "/admin.messaging.v1.MessagingService/ListMessages",
            request_serializer=app_dot_routes_dot_pb_dot_messaging__pb2.ListMessagesRequest.SerializeToString,
            response_deserializer=app_dot_routes_dot_pb_dot_messaging__pb2.ListMessagesResponse.FromString,
            _registered_method=True,
        )
        self.MarkRead = channel.unary_unary(
            "/admin.messaging.v1.MessagingService/MarkRead",
            request_serializer=app_dot_routes_dot_pb_dot_messaging__pb2.MarkReadRequest.SerializeToString,
            response_deserializer=app_dot_routes_dot_pb_dot_messaging__pb2.MarkReadResponse.FromString,
            _registered_method=True,
        )


class MessagingServiceServicer:
    """MessagingService — candidate <-> recruiter chat, 1:1 with an application. Authed;
    sender identity from the token (no impersonation); authz reuses the application owner.
    """

    def SendMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListThreads(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def MarkRead(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_MessagingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "SendMessage": grpc.unary_unary_rpc_method_handler(
            servicer.SendMessage,
            request_deserializer=app_dot_routes_dot_pb_dot_messaging__pb2.SendMessageRequest.FromString,
            response_serializer=app_dot_routes_dot_pb_dot_messaging__pb2.MessageDTO.SerializeToString,
        ),
        "ListThreads": grpc.unary_unary_rpc_method_handler(
            servicer.ListThreads,
            request_deserializer=app_dot_routes_dot_pb_dot_messaging__pb2.ListThreadsRequest.FromString,
            response_serializer=app_dot_routes_dot_pb_dot_messaging__pb2.ListThreadsResponse.SerializeToString,
        ),
        "ListMessages": grpc.unary_unary_rpc_method_handler(
            servicer.ListMessages,
            request_deserializer=app_dot_routes_dot_pb_dot_messaging__pb2.ListMessagesRequest.FromString,
            response_serializer=app_dot_routes_dot_pb_dot_messaging__pb2.ListMessagesResponse.SerializeToString,
        ),
        "MarkRead": grpc.unary_unary_rpc_method_handler(
            servicer.MarkRead,
            request_deserializer=app_dot_routes_dot_pb_dot_messaging__pb2.MarkReadRequest.FromString,
            response_serializer=app_dot_routes_dot_pb_dot_messaging__pb2.MarkReadResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "admin.messaging.v1.MessagingService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "admin.messaging.v1.MessagingService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class MessagingService:
    """MessagingService — candidate <-> recruiter chat, 1:1 with an application. Authed;
    sender identity from the token (no impersonation); authz reuses the application owner.
    """

    @staticmethod
    def SendMessage(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/admin.messaging.v1.MessagingService/SendMessage",
            app_dot_routes_dot_pb_dot_messaging__pb2.SendMessageRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_messaging__pb2.MessageDTO.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListThreads(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/admin.messaging.v1.MessagingService/ListThreads",
            app_dot_routes_dot_pb_dot_messaging__pb2.ListThreadsRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_messaging__pb2.ListThreadsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListMessages(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/admin.messaging.v1.MessagingService/ListMessages",
            app_dot_routes_dot_pb_dot_messaging__pb2.ListMessagesRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_messaging__pb2.ListMessagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def MarkRead(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/admin.messaging.v1.MessagingService/MarkRead",
            app_dot_routes_dot_pb_dot_messaging__pb2.MarkReadRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_messaging__pb2.MarkReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
