# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

from app.routes.pb import (
    notification_pb2 as app_dot_routes_dot_pb_dot_notification__pb2,
)

GRPC_GENERATED_VERSION = "1.81.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in app/routes/pb/notification_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class NotificationServiceStub:
    """NotificationService — a recipient's notification feed + read-acks. Every RPC is
    recipient-scoped to the caller (caller_identity); no comp-scoping at the service.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListNotifications = channel.unary_unary(
            "/admin.notification.v1.NotificationService/ListNotifications",
            request_serializer=app_dot_routes_dot_pb_dot_notification__pb2.ListRequest.SerializeToString,
            response_deserializer=app_dot_routes_dot_pb_dot_notification__pb2.ListResponse.FromString,
            _registered_method=True,
        )
        self.MarkRead = channel.unary_unary(
            "/admin.notification.v1.NotificationService/MarkRead",
            request_serializer=app_dot_routes_dot_pb_dot_notification__pb2.MarkReadRequest.SerializeToString,
            response_deserializer=app_dot_routes_dot_pb_dot_notification__pb2.MarkReadResponse.FromString,
            _registered_method=True,
        )
        self.MarkAllRead = channel.unary_unary(
            "/admin.notification.v1.NotificationService/MarkAllRead",
            request_serializer=app_dot_routes_dot_pb_dot_notification__pb2.MarkAllReadRequest.SerializeToString,
            response_deserializer=app_dot_routes_dot_pb_dot_notification__pb2.MarkReadResponse.FromString,
            _registered_method=True,
        )


class NotificationServiceServicer:
    """NotificationService — a recipient's notification feed + read-acks. Every RPC is
    recipient-scoped to the caller (caller_identity); no comp-scoping at the service.
    """

    def ListNotifications(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def MarkRead(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def MarkAllRead(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_NotificationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "ListNotifications": grpc.unary_unary_rpc_method_handler(
            servicer.ListNotifications,
            request_deserializer=app_dot_routes_dot_pb_dot_notification__pb2.ListRequest.FromString,
            response_serializer=app_dot_routes_dot_pb_dot_notification__pb2.ListResponse.SerializeToString,
        ),
        "MarkRead": grpc.unary_unary_rpc_method_handler(
            servicer.MarkRead,
            request_deserializer=app_dot_routes_dot_pb_dot_notification__pb2.MarkReadRequest.FromString,
            response_serializer=app_dot_routes_dot_pb_dot_notification__pb2.MarkReadResponse.SerializeToString,
        ),
        "MarkAllRead": grpc.unary_unary_rpc_method_handler(
            servicer.MarkAllRead,
            request_deserializer=app_dot_routes_dot_pb_dot_notification__pb2.MarkAllReadRequest.FromString,
            response_serializer=app_dot_routes_dot_pb_dot_notification__pb2.MarkReadResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "admin.notification.v1.NotificationService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "admin.notification.v1.NotificationService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class NotificationService:
    """NotificationService — a recipient's notification feed + read-acks. Every RPC is
    recipient-scoped to the caller (caller_identity); no comp-scoping at the service.
    """

    @staticmethod
    def ListNotifications(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/admin.notification.v1.NotificationService/ListNotifications",
            app_dot_routes_dot_pb_dot_notification__pb2.ListRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_notification__pb2.ListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def MarkRead(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/admin.notification.v1.NotificationService/MarkRead",
            app_dot_routes_dot_pb_dot_notification__pb2.MarkReadRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_notification__pb2.MarkReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def MarkAllRead(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/admin.notification.v1.NotificationService/MarkAllRead",
            app_dot_routes_dot_pb_dot_notification__pb2.MarkAllReadRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_notification__pb2.MarkReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
