# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/routes/pb/observability.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 33, 5, "", "app/routes/pb/observability.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n!app/routes/pb/observability.proto\x12\x16\x61\x64min.observability.v1"O\n\x12\x43lientErrorPayload\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x1a\n\x12stack_truncated_8k\x18\x03 \x01(\t"\xdd\x01\n\x10\x43lientErrorEvent\x12\x16\n\x0e\x63orrelation_id\x18\x01 \x01(\t\x12\x10\n\x08\x65vent_id\x18\x02 \x01(\t\x12\x16\n\x0eoccurred_at_ms\x18\x03 \x01(\x03\x12\x11\n\tcomponent\x18\x04 \x01(\t\x12\r\n\x05route\x18\x05 \x01(\t\x12\x11\n\tbuild_sha\x18\x06 \x01(\t\x12\x17\n\x0fuser_agent_hash\x18\x07 \x01(\t\x12\x39\n\x05\x65rror\x18\x08 \x01(\x0b\x32*.admin.observability.v1.ClientErrorPayload"T\n\x18RecordClientErrorRequest\x12\x38\n\x06\x65vents\x18\x01 \x03(\x0b\x32(.admin.observability.v1.ClientErrorEvent"7\n\x19RecordClientErrorResponse\x12\x1a\n\x12\x61\x63\x63\x65pted_event_ids\x18\x01 \x03(\t"\x85\x01\n\x0b\x43lientEvent\x12\x16\n\x0e\x63orrelation_id\x18\x01 \x01(\t\x12\x10\n\x08\x65vent_id\x18\x02 \x01(\t\x12\x16\n\x0eoccurred_at_ms\x18\x03 \x01(\x03\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\r\n\x05route\x18\x05 \x01(\t\x12\x17\n\x0fproperties_json\x18\x06 \x01(\t"O\n\x18RecordClientEventRequest\x12\x33\n\x06\x65vents\x18\x01 \x03(\x0b\x32#.admin.observability.v1.ClientEvent"7\n\x19RecordClientEventResponse\x12\x1a\n\x12\x61\x63\x63\x65pted_event_ids\x18\x01 \x03(\t2\x8a\x02\n\x14ObservabilityService\x12x\n\x11RecordClientError\x12\x30.admin.observability.v1.RecordClientErrorRequest\x1a\x31.admin.observability.v1.RecordClientErrorResponse\x12x\n\x11RecordClientEvent\x12\x30.admin.observability.v1.RecordClientEventRequest\x1a\x31.admin.observability.v1.RecordClientEventResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "app.routes.pb.observability_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_CLIENTERRORPAYLOAD"]._serialized_start = 61
    _globals["_CLIENTERRORPAYLOAD"]._serialized_end = 140
    _globals["_CLIENTERROREVENT"]._serialized_start = 143
    _globals["_CLIENTERROREVENT"]._serialized_end = 364
    _globals["_RECORDCLIENTERRORREQUEST"]._serialized_start = 366
    _globals["_RECORDCLIENTERRORREQUEST"]._serialized_end = 450
    _globals["_RECORDCLIENTERRORRESPONSE"]._serialized_start = 452
    _globals["_RECORDCLIENTERRORRESPONSE"]._serialized_end = 507
    _globals["_CLIENTEVENT"]._serialized_start = 510
    _globals["_CLIENTEVENT"]._serialized_end = 643
    _globals["_RECORDCLIENTEVENTREQUEST"]._serialized_start = 645
    _globals["_RECORDCLIENTEVENTREQUEST"]._serialized_end = 724
    _globals["_RECORDCLIENTEVENTRESPONSE"]._serialized_start = 726
    _globals["_RECORDCLIENTEVENTRESPONSE"]._serialized_end = 781
    _globals["_OBSERVABILITYSERVICE"]._serialized_start = 784
    _globals["_OBSERVABILITYSERVICE"]._serialized_end = 1050
# @@protoc_insertion_point(module_scope)
