# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""


import grpc

from app.routes.pb import (
    observability_pb2 as app_dot_routes_dot_pb_dot_observability__pb2,
)

GRPC_GENERATED_VERSION = "1.81.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in app/routes/pb/observability_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class ObservabilityServiceStub:
    """ObservabilityService — FE → BE pipe for unhandled client errors + analytics events.
    Both RPCs idempotent on event_id (24h Redis SET dedup). Server-side identity
    enforcement: the request's context is DISCARDED; user_id/comp_id/role come from
    the access token (anonymous calls leave them null).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RecordClientError = channel.unary_unary(
            "/admin.observability.v1.ObservabilityService/RecordClientError",
            request_serializer=app_dot_routes_dot_pb_dot_observability__pb2.RecordClientErrorRequest.SerializeToString,
            response_deserializer=app_dot_routes_dot_pb_dot_observability__pb2.RecordClientErrorResponse.FromString,
            _registered_method=True,
        )
        self.RecordClientEvent = channel.unary_unary(
            "/admin.observability.v1.ObservabilityService/RecordClientEvent",
            request_serializer=app_dot_routes_dot_pb_dot_observability__pb2.RecordClientEventRequest.SerializeToString,
            response_deserializer=app_dot_routes_dot_pb_dot_observability__pb2.RecordClientEventResponse.FromString,
            _registered_method=True,
        )


class ObservabilityServiceServicer:
    """ObservabilityService — FE → BE pipe for unhandled client errors + analytics events.
    Both RPCs idempotent on event_id (24h Redis SET dedup). Server-side identity
    enforcement: the request's context is DISCARDED; user_id/comp_id/role come from
    the access token (anonymous calls leave them null).
    """

    def RecordClientError(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RecordClientEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ObservabilityServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "RecordClientError": grpc.unary_unary_rpc_method_handler(
            servicer.RecordClientError,
            request_deserializer=app_dot_routes_dot_pb_dot_observability__pb2.RecordClientErrorRequest.FromString,
            response_serializer=app_dot_routes_dot_pb_dot_observability__pb2.RecordClientErrorResponse.SerializeToString,
        ),
        "RecordClientEvent": grpc.unary_unary_rpc_method_handler(
            servicer.RecordClientEvent,
            request_deserializer=app_dot_routes_dot_pb_dot_observability__pb2.RecordClientEventRequest.FromString,
            response_serializer=app_dot_routes_dot_pb_dot_observability__pb2.RecordClientEventResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "admin.observability.v1.ObservabilityService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "admin.observability.v1.ObservabilityService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class ObservabilityService:
    """ObservabilityService — FE → BE pipe for unhandled client errors + analytics events.
    Both RPCs idempotent on event_id (24h Redis SET dedup). Server-side identity
    enforcement: the request's context is DISCARDED; user_id/comp_id/role come from
    the access token (anonymous calls leave them null).
    """

    @staticmethod
    def RecordClientError(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/admin.observability.v1.ObservabilityService/RecordClientError",
            app_dot_routes_dot_pb_dot_observability__pb2.RecordClientErrorRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_observability__pb2.RecordClientErrorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def RecordClientEvent(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/admin.observability.v1.ObservabilityService/RecordClientEvent",
            app_dot_routes_dot_pb_dot_observability__pb2.RecordClientEventRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_observability__pb2.RecordClientEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
