# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.routes.pb import profile_pb2 as app_dot_routes_dot_pb_dot_profile__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in app/routes/pb/profile_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProfileServiceStub:
    """ProfileService — candidate profile + resume. Auth via `authorization` metadata;
    the caller's identity (from the access token) is the profile owner.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadResume = channel.unary_unary(
                '/admin.profile.v1.ProfileService/UploadResume',
                request_serializer=app_dot_routes_dot_pb_dot_profile__pb2.UploadResumeRequest.SerializeToString,
                response_deserializer=app_dot_routes_dot_pb_dot_profile__pb2.ProfileResponse.FromString,
                _registered_method=True)
        self.GetProfile = channel.unary_unary(
                '/admin.profile.v1.ProfileService/GetProfile',
                request_serializer=app_dot_routes_dot_pb_dot_profile__pb2.GetProfileRequest.SerializeToString,
                response_deserializer=app_dot_routes_dot_pb_dot_profile__pb2.ProfileResponse.FromString,
                _registered_method=True)
        self.UpdateProfile = channel.unary_unary(
                '/admin.profile.v1.ProfileService/UpdateProfile',
                request_serializer=app_dot_routes_dot_pb_dot_profile__pb2.UpdateProfileRequest.SerializeToString,
                response_deserializer=app_dot_routes_dot_pb_dot_profile__pb2.ProfileResponse.FromString,
                _registered_method=True)


class ProfileServiceServicer:
    """ProfileService — candidate profile + resume. Auth via `authorization` metadata;
    the caller's identity (from the access token) is the profile owner.
    """

    def UploadResume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProfileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadResume': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadResume,
                    request_deserializer=app_dot_routes_dot_pb_dot_profile__pb2.UploadResumeRequest.FromString,
                    response_serializer=app_dot_routes_dot_pb_dot_profile__pb2.ProfileResponse.SerializeToString,
            ),
            'GetProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProfile,
                    request_deserializer=app_dot_routes_dot_pb_dot_profile__pb2.GetProfileRequest.FromString,
                    response_serializer=app_dot_routes_dot_pb_dot_profile__pb2.ProfileResponse.SerializeToString,
            ),
            'UpdateProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProfile,
                    request_deserializer=app_dot_routes_dot_pb_dot_profile__pb2.UpdateProfileRequest.FromString,
                    response_serializer=app_dot_routes_dot_pb_dot_profile__pb2.ProfileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'admin.profile.v1.ProfileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('admin.profile.v1.ProfileService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProfileService:
    """ProfileService — candidate profile + resume. Auth via `authorization` metadata;
    the caller's identity (from the access token) is the profile owner.
    """

    @staticmethod
    def UploadResume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.profile.v1.ProfileService/UploadResume',
            app_dot_routes_dot_pb_dot_profile__pb2.UploadResumeRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_profile__pb2.ProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.profile.v1.ProfileService/GetProfile',
            app_dot_routes_dot_pb_dot_profile__pb2.GetProfileRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_profile__pb2.ProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.profile.v1.ProfileService/UpdateProfile',
            app_dot_routes_dot_pb_dot_profile__pb2.UpdateProfileRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_profile__pb2.ProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
