# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/routes/pb/profile.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'app/routes/pb/profile.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x61pp/routes/pb/profile.proto\x12\x10\x61\x64min.profile.v1\"A\n\x0e\x45xperienceItem\x12\x0f\n\x07\x63ompany\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07summary\x18\x03 \x01(\t\"B\n\rEducationItem\x12\x13\n\x0binstitution\x18\x01 \x01(\t\x12\x0e\n\x06\x64\x65gree\x18\x02 \x01(\t\x12\x0c\n\x04year\x18\x03 \x01(\t\"\xf7\x01\n\x14UpdateProfileRequest\x12\x11\n\tfull_name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\x12\x10\n\x08location\x18\x03 \x01(\t\x12\x1b\n\x13willing_to_relocate\x18\x04 \x01(\x08\x12\x16\n\x0ejob_preference\x18\x05 \x01(\t\x12\x34\n\nexperience\x18\x06 \x03(\x0b\x32 .admin.profile.v1.ExperienceItem\x12\x32\n\teducation\x18\x07 \x03(\x0b\x32\x1f.admin.profile.v1.EducationItem\x12\x0e\n\x06skills\x18\x08 \x03(\t\"9\n\x13UploadResumeRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x14\n\x0c\x63ontent_type\x18\x02 \x01(\t\"\x13\n\x11GetProfileRequest\"\xd5\x02\n\x0fProfileResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x17\n\x0fresume_uploaded\x18\x02 \x01(\x08\x12\x0e\n\x06parsed\x18\x03 \x01(\x08\x12\x11\n\tconfirmed\x18\x04 \x01(\x08\x12\x14\n\x0c\x63ompleteness\x18\x05 \x01(\x05\x12\x11\n\tfull_name\x18\x06 \x01(\t\x12\x0b\n\x03\x61ge\x18\x07 \x01(\x05\x12\x10\n\x08location\x18\x08 \x01(\t\x12\x1b\n\x13willing_to_relocate\x18\t \x01(\x08\x12\x16\n\x0ejob_preference\x18\n \x01(\t\x12\x34\n\nexperience\x18\x0b \x03(\x0b\x32 .admin.profile.v1.ExperienceItem\x12\x32\n\teducation\x18\x0c \x03(\x0b\x32\x1f.admin.profile.v1.EducationItem\x12\x0e\n\x06skills\x18\r \x03(\t2\x9c\x02\n\x0eProfileService\x12X\n\x0cUploadResume\x12%.admin.profile.v1.UploadResumeRequest\x1a!.admin.profile.v1.ProfileResponse\x12T\n\nGetProfile\x12#.admin.profile.v1.GetProfileRequest\x1a!.admin.profile.v1.ProfileResponse\x12Z\n\rUpdateProfile\x12&.admin.profile.v1.UpdateProfileRequest\x1a!.admin.profile.v1.ProfileResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.routes.pb.profile_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EXPERIENCEITEM']._serialized_start=49
  _globals['_EXPERIENCEITEM']._serialized_end=114
  _globals['_EDUCATIONITEM']._serialized_start=116
  _globals['_EDUCATIONITEM']._serialized_end=182
  _globals['_UPDATEPROFILEREQUEST']._serialized_start=185
  _globals['_UPDATEPROFILEREQUEST']._serialized_end=432
  _globals['_UPLOADRESUMEREQUEST']._serialized_start=434
  _globals['_UPLOADRESUMEREQUEST']._serialized_end=491
  _globals['_GETPROFILEREQUEST']._serialized_start=493
  _globals['_GETPROFILEREQUEST']._serialized_end=512
  _globals['_PROFILERESPONSE']._serialized_start=515
  _globals['_PROFILERESPONSE']._serialized_end=856
  _globals['_PROFILESERVICE']._serialized_start=859
  _globals['_PROFILESERVICE']._serialized_end=1143
# @@protoc_insertion_point(module_scope)
