# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/routes/pb/report.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'app/routes/pb/report.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x61pp/routes/pb/report.proto\x12\x0f\x61\x64min.report.v1\"*\n\x10GetReportRequest\x12\x16\n\x0e\x61pplication_id\x18\x01 \x01(\t\"$\n\x12ListReportsRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\"\xc0\x01\n\x0fInterviewReport\x12\x16\n\x0e\x61pplication_id\x18\x01 \x01(\t\x12\x19\n\x11\x63\x61ndidate_user_id\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\t\x12\x19\n\x11\x65xecutive_summary\x18\x04 \x01(\t\x12\x12\n\nhighlights\x18\x05 \x03(\t\x12\r\n\x05risks\x18\x06 \x03(\t\x12\x15\n\roverall_score\x18\x07 \x01(\x01\x12\x16\n\x0erecommendation\x18\x08 \x01(\t\"?\n\nReportList\x12\x31\n\x07reports\x18\x01 \x03(\x0b\x32 .admin.report.v1.InterviewReport\"1\n\x0cReportExport\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\x32\x87\x02\n\rReportService\x12P\n\tGetReport\x12!.admin.report.v1.GetReportRequest\x1a .admin.report.v1.InterviewReport\x12O\n\x0bListReports\x12#.admin.report.v1.ListReportsRequest\x1a\x1b.admin.report.v1.ReportList\x12S\n\rExportReports\x12#.admin.report.v1.ListReportsRequest\x1a\x1d.admin.report.v1.ReportExportb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.routes.pb.report_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETREPORTREQUEST']._serialized_start=47
  _globals['_GETREPORTREQUEST']._serialized_end=89
  _globals['_LISTREPORTSREQUEST']._serialized_start=91
  _globals['_LISTREPORTSREQUEST']._serialized_end=127
  _globals['_INTERVIEWREPORT']._serialized_start=130
  _globals['_INTERVIEWREPORT']._serialized_end=322
  _globals['_REPORTLIST']._serialized_start=324
  _globals['_REPORTLIST']._serialized_end=387
  _globals['_REPORTEXPORT']._serialized_start=389
  _globals['_REPORTEXPORT']._serialized_end=438
  _globals['_REPORTSERVICE']._serialized_start=441
  _globals['_REPORTSERVICE']._serialized_end=704
# @@protoc_insertion_point(module_scope)
