# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.routes.pb import report_pb2 as app_dot_routes_dot_pb_dot_report__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in app/routes/pb/report_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ReportServiceStub:
    """ReportService — recruiters read the AI-generated interview report for scored
    applications in their company. Read-only, manager-only, comp_id-scoped (via the
    application, the source of truth for tenant + funnel state).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetReport = channel.unary_unary(
                '/admin.report.v1.ReportService/GetReport',
                request_serializer=app_dot_routes_dot_pb_dot_report__pb2.GetReportRequest.SerializeToString,
                response_deserializer=app_dot_routes_dot_pb_dot_report__pb2.InterviewReport.FromString,
                _registered_method=True)
        self.ListReports = channel.unary_unary(
                '/admin.report.v1.ReportService/ListReports',
                request_serializer=app_dot_routes_dot_pb_dot_report__pb2.ListReportsRequest.SerializeToString,
                response_deserializer=app_dot_routes_dot_pb_dot_report__pb2.ReportList.FromString,
                _registered_method=True)
        self.ExportReports = channel.unary_unary(
                '/admin.report.v1.ReportService/ExportReports',
                request_serializer=app_dot_routes_dot_pb_dot_report__pb2.ListReportsRequest.SerializeToString,
                response_deserializer=app_dot_routes_dot_pb_dot_report__pb2.ReportExport.FromString,
                _registered_method=True)
        self.GetIntegrityTimeline = channel.unary_unary(
                '/admin.report.v1.ReportService/GetIntegrityTimeline',
                request_serializer=app_dot_routes_dot_pb_dot_report__pb2.GetIntegrityTimelineRequest.SerializeToString,
                response_deserializer=app_dot_routes_dot_pb_dot_report__pb2.IntegrityTimeline.FromString,
                _registered_method=True)


class ReportServiceServicer:
    """ReportService — recruiters read the AI-generated interview report for scored
    applications in their company. Read-only, manager-only, comp_id-scoped (via the
    application, the source of truth for tenant + funnel state).
    """

    def GetReport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListReports(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExportReports(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIntegrityTimeline(self, request, context):
        """Recruiter integrity timeline — the first reader of proctoring_events (comp-scoped).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReportServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetReport': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReport,
                    request_deserializer=app_dot_routes_dot_pb_dot_report__pb2.GetReportRequest.FromString,
                    response_serializer=app_dot_routes_dot_pb_dot_report__pb2.InterviewReport.SerializeToString,
            ),
            'ListReports': grpc.unary_unary_rpc_method_handler(
                    servicer.ListReports,
                    request_deserializer=app_dot_routes_dot_pb_dot_report__pb2.ListReportsRequest.FromString,
                    response_serializer=app_dot_routes_dot_pb_dot_report__pb2.ReportList.SerializeToString,
            ),
            'ExportReports': grpc.unary_unary_rpc_method_handler(
                    servicer.ExportReports,
                    request_deserializer=app_dot_routes_dot_pb_dot_report__pb2.ListReportsRequest.FromString,
                    response_serializer=app_dot_routes_dot_pb_dot_report__pb2.ReportExport.SerializeToString,
            ),
            'GetIntegrityTimeline': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIntegrityTimeline,
                    request_deserializer=app_dot_routes_dot_pb_dot_report__pb2.GetIntegrityTimelineRequest.FromString,
                    response_serializer=app_dot_routes_dot_pb_dot_report__pb2.IntegrityTimeline.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'admin.report.v1.ReportService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('admin.report.v1.ReportService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReportService:
    """ReportService — recruiters read the AI-generated interview report for scored
    applications in their company. Read-only, manager-only, comp_id-scoped (via the
    application, the source of truth for tenant + funnel state).
    """

    @staticmethod
    def GetReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.report.v1.ReportService/GetReport',
            app_dot_routes_dot_pb_dot_report__pb2.GetReportRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_report__pb2.InterviewReport.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListReports(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.report.v1.ReportService/ListReports',
            app_dot_routes_dot_pb_dot_report__pb2.ListReportsRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_report__pb2.ReportList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExportReports(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.report.v1.ReportService/ExportReports',
            app_dot_routes_dot_pb_dot_report__pb2.ListReportsRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_report__pb2.ReportExport.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetIntegrityTimeline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.report.v1.ReportService/GetIntegrityTimeline',
            app_dot_routes_dot_pb_dot_report__pb2.GetIntegrityTimelineRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_report__pb2.IntegrityTimeline.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
