# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/routes/pb/rubric.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'app/routes/pb/rubric.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x61pp/routes/pb/rubric.proto\x12\x0f\x61\x64min.rubric.v1\"*\n\nCompetency\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06weight\x18\x02 \x01(\x01\"U\n\x06Rubric\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x31\n\x0c\x63ompetencies\x18\x03 \x03(\x0b\x32\x1b.admin.rubric.v1.Competency\"V\n\x13\x43reateRubricRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x31\n\x0c\x63ompetencies\x18\x02 \x03(\x0b\x32\x1b.admin.rubric.v1.Competency\"\x14\n\x12ListRubricsRequest\"b\n\x13UpdateRubricRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x31\n\x0c\x63ompetencies\x18\x03 \x03(\x0b\x32\x1b.admin.rubric.v1.Competency\"!\n\x13\x44\x65leteRubricRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\"\n\x14\x44\x65leteRubricResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\"6\n\nRubricList\x12(\n\x07rubrics\x18\x01 \x03(\x0b\x32\x17.admin.rubric.v1.Rubric2\xdb\x02\n\rRubricService\x12M\n\x0c\x43reateRubric\x12$.admin.rubric.v1.CreateRubricRequest\x1a\x17.admin.rubric.v1.Rubric\x12O\n\x0bListRubrics\x12#.admin.rubric.v1.ListRubricsRequest\x1a\x1b.admin.rubric.v1.RubricList\x12M\n\x0cUpdateRubric\x12$.admin.rubric.v1.UpdateRubricRequest\x1a\x17.admin.rubric.v1.Rubric\x12[\n\x0c\x44\x65leteRubric\x12$.admin.rubric.v1.DeleteRubricRequest\x1a%.admin.rubric.v1.DeleteRubricResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.routes.pb.rubric_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMPETENCY']._serialized_start=47
  _globals['_COMPETENCY']._serialized_end=89
  _globals['_RUBRIC']._serialized_start=91
  _globals['_RUBRIC']._serialized_end=176
  _globals['_CREATERUBRICREQUEST']._serialized_start=178
  _globals['_CREATERUBRICREQUEST']._serialized_end=264
  _globals['_LISTRUBRICSREQUEST']._serialized_start=266
  _globals['_LISTRUBRICSREQUEST']._serialized_end=286
  _globals['_UPDATERUBRICREQUEST']._serialized_start=288
  _globals['_UPDATERUBRICREQUEST']._serialized_end=386
  _globals['_DELETERUBRICREQUEST']._serialized_start=388
  _globals['_DELETERUBRICREQUEST']._serialized_end=421
  _globals['_DELETERUBRICRESPONSE']._serialized_start=423
  _globals['_DELETERUBRICRESPONSE']._serialized_end=457
  _globals['_RUBRICLIST']._serialized_start=459
  _globals['_RUBRICLIST']._serialized_end=513
  _globals['_RUBRICSERVICE']._serialized_start=516
  _globals['_RUBRICSERVICE']._serialized_end=863
# @@protoc_insertion_point(module_scope)
