# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.routes.pb import saved_jobs_pb2 as app_dot_routes_dot_pb_dot_saved__jobs__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in app/routes/pb/saved_jobs_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SavedJobsServiceStub:
    """SavedJobsService — a candidate's job bookmarks. Every RPC derives the candidate from
    the bearer token (caller_identity); `candidate_user_id` is NEVER a request field. Save
    is idempotent (unique (candidate_user_id, job_id)); a saved job that later unpublishes
    is filtered out of the list (the bookmark row stays harmless).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SaveJob = channel.unary_unary(
                '/admin.saved_jobs.v1.SavedJobsService/SaveJob',
                request_serializer=app_dot_routes_dot_pb_dot_saved__jobs__pb2.SaveJobRequest.SerializeToString,
                response_deserializer=app_dot_routes_dot_pb_dot_saved__jobs__pb2.SaveJobResponse.FromString,
                _registered_method=True)
        self.UnsaveJob = channel.unary_unary(
                '/admin.saved_jobs.v1.SavedJobsService/UnsaveJob',
                request_serializer=app_dot_routes_dot_pb_dot_saved__jobs__pb2.UnsaveJobRequest.SerializeToString,
                response_deserializer=app_dot_routes_dot_pb_dot_saved__jobs__pb2.UnsaveJobResponse.FromString,
                _registered_method=True)
        self.ListSavedJobs = channel.unary_unary(
                '/admin.saved_jobs.v1.SavedJobsService/ListSavedJobs',
                request_serializer=app_dot_routes_dot_pb_dot_saved__jobs__pb2.ListSavedJobsRequest.SerializeToString,
                response_deserializer=app_dot_routes_dot_pb_dot_saved__jobs__pb2.ListSavedJobsResponse.FromString,
                _registered_method=True)


class SavedJobsServiceServicer:
    """SavedJobsService — a candidate's job bookmarks. Every RPC derives the candidate from
    the bearer token (caller_identity); `candidate_user_id` is NEVER a request field. Save
    is idempotent (unique (candidate_user_id, job_id)); a saved job that later unpublishes
    is filtered out of the list (the bookmark row stays harmless).
    """

    def SaveJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnsaveJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSavedJobs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SavedJobsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SaveJob': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveJob,
                    request_deserializer=app_dot_routes_dot_pb_dot_saved__jobs__pb2.SaveJobRequest.FromString,
                    response_serializer=app_dot_routes_dot_pb_dot_saved__jobs__pb2.SaveJobResponse.SerializeToString,
            ),
            'UnsaveJob': grpc.unary_unary_rpc_method_handler(
                    servicer.UnsaveJob,
                    request_deserializer=app_dot_routes_dot_pb_dot_saved__jobs__pb2.UnsaveJobRequest.FromString,
                    response_serializer=app_dot_routes_dot_pb_dot_saved__jobs__pb2.UnsaveJobResponse.SerializeToString,
            ),
            'ListSavedJobs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSavedJobs,
                    request_deserializer=app_dot_routes_dot_pb_dot_saved__jobs__pb2.ListSavedJobsRequest.FromString,
                    response_serializer=app_dot_routes_dot_pb_dot_saved__jobs__pb2.ListSavedJobsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'admin.saved_jobs.v1.SavedJobsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('admin.saved_jobs.v1.SavedJobsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SavedJobsService:
    """SavedJobsService — a candidate's job bookmarks. Every RPC derives the candidate from
    the bearer token (caller_identity); `candidate_user_id` is NEVER a request field. Save
    is idempotent (unique (candidate_user_id, job_id)); a saved job that later unpublishes
    is filtered out of the list (the bookmark row stays harmless).
    """

    @staticmethod
    def SaveJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.saved_jobs.v1.SavedJobsService/SaveJob',
            app_dot_routes_dot_pb_dot_saved__jobs__pb2.SaveJobRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_saved__jobs__pb2.SaveJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnsaveJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.saved_jobs.v1.SavedJobsService/UnsaveJob',
            app_dot_routes_dot_pb_dot_saved__jobs__pb2.UnsaveJobRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_saved__jobs__pb2.UnsaveJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSavedJobs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.saved_jobs.v1.SavedJobsService/ListSavedJobs',
            app_dot_routes_dot_pb_dot_saved__jobs__pb2.ListSavedJobsRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_saved__jobs__pb2.ListSavedJobsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
