# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.routes.pb import settings_pb2 as app_dot_routes_dot_pb_dot_settings__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in app/routes/pb/settings_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SettingsServiceStub:
    """SettingsService — self-scoped account settings (the caller is the token; no request
    carries a target user_id). This slice ships notification preferences; sessions / 2FA /
    password+email change land additively on the same service.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetNotificationPrefs = channel.unary_unary(
                '/admin.settings.v1.SettingsService/GetNotificationPrefs',
                request_serializer=app_dot_routes_dot_pb_dot_settings__pb2.GetNotificationPrefsRequest.SerializeToString,
                response_deserializer=app_dot_routes_dot_pb_dot_settings__pb2.NotificationPrefs.FromString,
                _registered_method=True)
        self.SetNotificationPrefs = channel.unary_unary(
                '/admin.settings.v1.SettingsService/SetNotificationPrefs',
                request_serializer=app_dot_routes_dot_pb_dot_settings__pb2.NotificationPrefs.SerializeToString,
                response_deserializer=app_dot_routes_dot_pb_dot_settings__pb2.NotificationPrefs.FromString,
                _registered_method=True)
        self.SetupTotp = channel.unary_unary(
                '/admin.settings.v1.SettingsService/SetupTotp',
                request_serializer=app_dot_routes_dot_pb_dot_settings__pb2.SetupTotpRequest.SerializeToString,
                response_deserializer=app_dot_routes_dot_pb_dot_settings__pb2.SetupTotpResponse.FromString,
                _registered_method=True)
        self.VerifyTotp = channel.unary_unary(
                '/admin.settings.v1.SettingsService/VerifyTotp',
                request_serializer=app_dot_routes_dot_pb_dot_settings__pb2.VerifyTotpRequest.SerializeToString,
                response_deserializer=app_dot_routes_dot_pb_dot_settings__pb2.VerifyTotpResponse.FromString,
                _registered_method=True)
        self.DisableTotp = channel.unary_unary(
                '/admin.settings.v1.SettingsService/DisableTotp',
                request_serializer=app_dot_routes_dot_pb_dot_settings__pb2.DisableTotpRequest.SerializeToString,
                response_deserializer=app_dot_routes_dot_pb_dot_settings__pb2.OkResponse.FromString,
                _registered_method=True)


class SettingsServiceServicer:
    """SettingsService — self-scoped account settings (the caller is the token; no request
    carries a target user_id). This slice ships notification preferences; sessions / 2FA /
    password+email change land additively on the same service.
    """

    def GetNotificationPrefs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetNotificationPrefs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetupTotp(self, request, context):
        """2FA (TOTP). SetupTotp stages an encrypted secret; VerifyTotp enables + returns
        one-time recovery codes; DisableTotp takes a TOTP code OR a recovery code.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyTotp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisableTotp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SettingsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetNotificationPrefs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNotificationPrefs,
                    request_deserializer=app_dot_routes_dot_pb_dot_settings__pb2.GetNotificationPrefsRequest.FromString,
                    response_serializer=app_dot_routes_dot_pb_dot_settings__pb2.NotificationPrefs.SerializeToString,
            ),
            'SetNotificationPrefs': grpc.unary_unary_rpc_method_handler(
                    servicer.SetNotificationPrefs,
                    request_deserializer=app_dot_routes_dot_pb_dot_settings__pb2.NotificationPrefs.FromString,
                    response_serializer=app_dot_routes_dot_pb_dot_settings__pb2.NotificationPrefs.SerializeToString,
            ),
            'SetupTotp': grpc.unary_unary_rpc_method_handler(
                    servicer.SetupTotp,
                    request_deserializer=app_dot_routes_dot_pb_dot_settings__pb2.SetupTotpRequest.FromString,
                    response_serializer=app_dot_routes_dot_pb_dot_settings__pb2.SetupTotpResponse.SerializeToString,
            ),
            'VerifyTotp': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyTotp,
                    request_deserializer=app_dot_routes_dot_pb_dot_settings__pb2.VerifyTotpRequest.FromString,
                    response_serializer=app_dot_routes_dot_pb_dot_settings__pb2.VerifyTotpResponse.SerializeToString,
            ),
            'DisableTotp': grpc.unary_unary_rpc_method_handler(
                    servicer.DisableTotp,
                    request_deserializer=app_dot_routes_dot_pb_dot_settings__pb2.DisableTotpRequest.FromString,
                    response_serializer=app_dot_routes_dot_pb_dot_settings__pb2.OkResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'admin.settings.v1.SettingsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('admin.settings.v1.SettingsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SettingsService:
    """SettingsService — self-scoped account settings (the caller is the token; no request
    carries a target user_id). This slice ships notification preferences; sessions / 2FA /
    password+email change land additively on the same service.
    """

    @staticmethod
    def GetNotificationPrefs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.settings.v1.SettingsService/GetNotificationPrefs',
            app_dot_routes_dot_pb_dot_settings__pb2.GetNotificationPrefsRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_settings__pb2.NotificationPrefs.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetNotificationPrefs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.settings.v1.SettingsService/SetNotificationPrefs',
            app_dot_routes_dot_pb_dot_settings__pb2.NotificationPrefs.SerializeToString,
            app_dot_routes_dot_pb_dot_settings__pb2.NotificationPrefs.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetupTotp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.settings.v1.SettingsService/SetupTotp',
            app_dot_routes_dot_pb_dot_settings__pb2.SetupTotpRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_settings__pb2.SetupTotpResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyTotp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.settings.v1.SettingsService/VerifyTotp',
            app_dot_routes_dot_pb_dot_settings__pb2.VerifyTotpRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_settings__pb2.VerifyTotpResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DisableTotp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.settings.v1.SettingsService/DisableTotp',
            app_dot_routes_dot_pb_dot_settings__pb2.DisableTotpRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_settings__pb2.OkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
