# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.routes.pb import sourcing_pb2 as app_dot_routes_dot_pb_dot_sourcing__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in app/routes/pb/sourcing_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SourcingServiceStub:
    """SourcingService — recruiter keyword search over the company's OWN applicants.
    Manager + comp-scoped (comp_id from the token); no global candidate index.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SearchCandidates = channel.unary_unary(
                '/admin.sourcing.v1.SourcingService/SearchCandidates',
                request_serializer=app_dot_routes_dot_pb_dot_sourcing__pb2.SearchCandidatesRequest.SerializeToString,
                response_deserializer=app_dot_routes_dot_pb_dot_sourcing__pb2.SearchCandidatesResponse.FromString,
                _registered_method=True)


class SourcingServiceServicer:
    """SourcingService — recruiter keyword search over the company's OWN applicants.
    Manager + comp-scoped (comp_id from the token); no global candidate index.
    """

    def SearchCandidates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SourcingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SearchCandidates': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchCandidates,
                    request_deserializer=app_dot_routes_dot_pb_dot_sourcing__pb2.SearchCandidatesRequest.FromString,
                    response_serializer=app_dot_routes_dot_pb_dot_sourcing__pb2.SearchCandidatesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'admin.sourcing.v1.SourcingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('admin.sourcing.v1.SourcingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SourcingService:
    """SourcingService — recruiter keyword search over the company's OWN applicants.
    Manager + comp-scoped (comp_id from the token); no global candidate index.
    """

    @staticmethod
    def SearchCandidates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.sourcing.v1.SourcingService/SearchCandidates',
            app_dot_routes_dot_pb_dot_sourcing__pb2.SearchCandidatesRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_sourcing__pb2.SearchCandidatesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
