# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.routes.pb import talent_pb2 as app_dot_routes_dot_pb_dot_talent__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in app/routes/pb/talent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TalentServiceStub:
    """TalentService — recruiters browse their company's talent pool: candidates who have
    applied to the company's jobs, with their application count. Comp-scoped, read-only.
    (Membership = applied-to-this-comp; explicit add-to-pool is a follow-up.)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTalentPool = channel.unary_unary(
                '/admin.talent.v1.TalentService/GetTalentPool',
                request_serializer=app_dot_routes_dot_pb_dot_talent__pb2.TalentPoolRequest.SerializeToString,
                response_deserializer=app_dot_routes_dot_pb_dot_talent__pb2.TalentPool.FromString,
                _registered_method=True)


class TalentServiceServicer:
    """TalentService — recruiters browse their company's talent pool: candidates who have
    applied to the company's jobs, with their application count. Comp-scoped, read-only.
    (Membership = applied-to-this-comp; explicit add-to-pool is a follow-up.)
    """

    def GetTalentPool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TalentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTalentPool': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTalentPool,
                    request_deserializer=app_dot_routes_dot_pb_dot_talent__pb2.TalentPoolRequest.FromString,
                    response_serializer=app_dot_routes_dot_pb_dot_talent__pb2.TalentPool.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'admin.talent.v1.TalentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('admin.talent.v1.TalentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TalentService:
    """TalentService — recruiters browse their company's talent pool: candidates who have
    applied to the company's jobs, with their application count. Comp-scoped, read-only.
    (Membership = applied-to-this-comp; explicit add-to-pool is a follow-up.)
    """

    @staticmethod
    def GetTalentPool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.talent.v1.TalentService/GetTalentPool',
            app_dot_routes_dot_pb_dot_talent__pb2.TalentPoolRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_talent__pb2.TalentPool.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
