# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.routes.pb import team_pb2 as app_dot_routes_dot_pb_dot_team__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in app/routes/pb/team_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TeamServiceStub:
    """TeamService — company seat management. Every mutation is team:manage-gated
    (company_admin only), comp_id-scoped, audited, and last-admin-protected.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListMembers = channel.unary_unary(
                '/admin.team.v1.TeamService/ListMembers',
                request_serializer=app_dot_routes_dot_pb_dot_team__pb2.ListMembersRequest.SerializeToString,
                response_deserializer=app_dot_routes_dot_pb_dot_team__pb2.ListMembersResponse.FromString,
                _registered_method=True)
        self.InviteMember = channel.unary_unary(
                '/admin.team.v1.TeamService/InviteMember',
                request_serializer=app_dot_routes_dot_pb_dot_team__pb2.InviteMemberRequest.SerializeToString,
                response_deserializer=app_dot_routes_dot_pb_dot_team__pb2.MemberDTO.FromString,
                _registered_method=True)
        self.ResendInvite = channel.unary_unary(
                '/admin.team.v1.TeamService/ResendInvite',
                request_serializer=app_dot_routes_dot_pb_dot_team__pb2.ResendInviteRequest.SerializeToString,
                response_deserializer=app_dot_routes_dot_pb_dot_team__pb2.MemberDTO.FromString,
                _registered_method=True)
        self.RevokeInvite = channel.unary_unary(
                '/admin.team.v1.TeamService/RevokeInvite',
                request_serializer=app_dot_routes_dot_pb_dot_team__pb2.RevokeInviteRequest.SerializeToString,
                response_deserializer=app_dot_routes_dot_pb_dot_team__pb2.MemberDTO.FromString,
                _registered_method=True)
        self.RemoveMember = channel.unary_unary(
                '/admin.team.v1.TeamService/RemoveMember',
                request_serializer=app_dot_routes_dot_pb_dot_team__pb2.RemoveMemberRequest.SerializeToString,
                response_deserializer=app_dot_routes_dot_pb_dot_team__pb2.MemberDTO.FromString,
                _registered_method=True)
        self.ChangeRole = channel.unary_unary(
                '/admin.team.v1.TeamService/ChangeRole',
                request_serializer=app_dot_routes_dot_pb_dot_team__pb2.ChangeRoleRequest.SerializeToString,
                response_deserializer=app_dot_routes_dot_pb_dot_team__pb2.MemberDTO.FromString,
                _registered_method=True)


class TeamServiceServicer:
    """TeamService — company seat management. Every mutation is team:manage-gated
    (company_admin only), comp_id-scoped, audited, and last-admin-protected.
    """

    def ListMembers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InviteMember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResendInvite(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeInvite(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveMember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangeRole(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TeamServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListMembers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMembers,
                    request_deserializer=app_dot_routes_dot_pb_dot_team__pb2.ListMembersRequest.FromString,
                    response_serializer=app_dot_routes_dot_pb_dot_team__pb2.ListMembersResponse.SerializeToString,
            ),
            'InviteMember': grpc.unary_unary_rpc_method_handler(
                    servicer.InviteMember,
                    request_deserializer=app_dot_routes_dot_pb_dot_team__pb2.InviteMemberRequest.FromString,
                    response_serializer=app_dot_routes_dot_pb_dot_team__pb2.MemberDTO.SerializeToString,
            ),
            'ResendInvite': grpc.unary_unary_rpc_method_handler(
                    servicer.ResendInvite,
                    request_deserializer=app_dot_routes_dot_pb_dot_team__pb2.ResendInviteRequest.FromString,
                    response_serializer=app_dot_routes_dot_pb_dot_team__pb2.MemberDTO.SerializeToString,
            ),
            'RevokeInvite': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeInvite,
                    request_deserializer=app_dot_routes_dot_pb_dot_team__pb2.RevokeInviteRequest.FromString,
                    response_serializer=app_dot_routes_dot_pb_dot_team__pb2.MemberDTO.SerializeToString,
            ),
            'RemoveMember': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveMember,
                    request_deserializer=app_dot_routes_dot_pb_dot_team__pb2.RemoveMemberRequest.FromString,
                    response_serializer=app_dot_routes_dot_pb_dot_team__pb2.MemberDTO.SerializeToString,
            ),
            'ChangeRole': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangeRole,
                    request_deserializer=app_dot_routes_dot_pb_dot_team__pb2.ChangeRoleRequest.FromString,
                    response_serializer=app_dot_routes_dot_pb_dot_team__pb2.MemberDTO.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'admin.team.v1.TeamService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('admin.team.v1.TeamService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TeamService:
    """TeamService — company seat management. Every mutation is team:manage-gated
    (company_admin only), comp_id-scoped, audited, and last-admin-protected.
    """

    @staticmethod
    def ListMembers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.team.v1.TeamService/ListMembers',
            app_dot_routes_dot_pb_dot_team__pb2.ListMembersRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_team__pb2.ListMembersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InviteMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.team.v1.TeamService/InviteMember',
            app_dot_routes_dot_pb_dot_team__pb2.InviteMemberRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_team__pb2.MemberDTO.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResendInvite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.team.v1.TeamService/ResendInvite',
            app_dot_routes_dot_pb_dot_team__pb2.ResendInviteRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_team__pb2.MemberDTO.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeInvite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.team.v1.TeamService/RevokeInvite',
            app_dot_routes_dot_pb_dot_team__pb2.RevokeInviteRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_team__pb2.MemberDTO.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.team.v1.TeamService/RemoveMember',
            app_dot_routes_dot_pb_dot_team__pb2.RemoveMemberRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_team__pb2.MemberDTO.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChangeRole(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.team.v1.TeamService/ChangeRole',
            app_dot_routes_dot_pb_dot_team__pb2.ChangeRoleRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_team__pb2.MemberDTO.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
