# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/routes/pb/team.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'app/routes/pb/team.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x61pp/routes/pb/team.proto\x12\radmin.team.v1\"p\n\tMemberDTO\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x0c\n\x04role\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\x16\n\x0elast_active_at\x18\x05 \x01(\t\x12\x12\n\ninvited_by\x18\x06 \x01(\t\"5\n\x12ListMembersRequest\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x11\n\tpage_size\x18\x02 \x01(\x05\"p\n\x13ListMembersResponse\x12)\n\x07members\x18\x01 \x03(\x0b\x32\x18.admin.team.v1.MemberDTO\x12\x0c\n\x04page\x18\x02 \x01(\x05\x12\x11\n\tpage_size\x18\x03 \x01(\x05\x12\r\n\x05total\x18\x04 \x01(\x05\"I\n\x13InviteMemberRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x0c\n\x04role\x18\x02 \x01(\t\x12\x15\n\rtemp_password\x18\x03 \x01(\t\"&\n\x13ResendInviteRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"&\n\x13RevokeInviteRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"&\n\x13RemoveMemberRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"2\n\x11\x43hangeRoleRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n\x04role\x18\x02 \x01(\t2\xe5\x03\n\x0bTeamService\x12T\n\x0bListMembers\x12!.admin.team.v1.ListMembersRequest\x1a\".admin.team.v1.ListMembersResponse\x12L\n\x0cInviteMember\x12\".admin.team.v1.InviteMemberRequest\x1a\x18.admin.team.v1.MemberDTO\x12L\n\x0cResendInvite\x12\".admin.team.v1.ResendInviteRequest\x1a\x18.admin.team.v1.MemberDTO\x12L\n\x0cRevokeInvite\x12\".admin.team.v1.RevokeInviteRequest\x1a\x18.admin.team.v1.MemberDTO\x12L\n\x0cRemoveMember\x12\".admin.team.v1.RemoveMemberRequest\x1a\x18.admin.team.v1.MemberDTO\x12H\n\nChangeRole\x12 .admin.team.v1.ChangeRoleRequest\x1a\x18.admin.team.v1.MemberDTOb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.routes.pb.team_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MEMBERDTO']._serialized_start=43
  _globals['_MEMBERDTO']._serialized_end=155
  _globals['_LISTMEMBERSREQUEST']._serialized_start=157
  _globals['_LISTMEMBERSREQUEST']._serialized_end=210
  _globals['_LISTMEMBERSRESPONSE']._serialized_start=212
  _globals['_LISTMEMBERSRESPONSE']._serialized_end=324
  _globals['_INVITEMEMBERREQUEST']._serialized_start=326
  _globals['_INVITEMEMBERREQUEST']._serialized_end=399
  _globals['_RESENDINVITEREQUEST']._serialized_start=401
  _globals['_RESENDINVITEREQUEST']._serialized_end=439
  _globals['_REVOKEINVITEREQUEST']._serialized_start=441
  _globals['_REVOKEINVITEREQUEST']._serialized_end=479
  _globals['_REMOVEMEMBERREQUEST']._serialized_start=481
  _globals['_REMOVEMEMBERREQUEST']._serialized_end=519
  _globals['_CHANGEROLEREQUEST']._serialized_start=521
  _globals['_CHANGEROLEREQUEST']._serialized_end=571
  _globals['_TEAMSERVICE']._serialized_start=574
  _globals['_TEAMSERVICE']._serialized_end=1059
# @@protoc_insertion_point(module_scope)
