# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/routes/pb/chat.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'app/routes/pb/chat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x61pp/routes/pb/chat.proto\x12\x10\x61iagents.chat.v1\",\n\x0b\x43hatMessage\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\">\n\x0b\x43hatRequest\x12/\n\x08messages\x18\x01 \x03(\x0b\x32\x1d.aiagents.chat.v1.ChatMessage\"7\n\x08\x43itation\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\r\n\x05topic\x18\x02 \x01(\t\x12\x0f\n\x07snippet\x18\x03 \x01(\t\"\x06\n\x04\x44one\"\x8d\x01\n\tChatEvent\x12\x0e\n\x04text\x18\x01 \x01(\tH\x00\x12.\n\x08\x63itation\x18\x02 \x01(\x0b\x32\x1a.aiagents.chat.v1.CitationH\x00\x12&\n\x04\x64one\x18\x03 \x01(\x0b\x32\x16.aiagents.chat.v1.DoneH\x00\x12\x0f\n\x05\x65rror\x18\x04 \x01(\tH\x00\x42\x07\n\x05\x65vent2S\n\x0b\x43hatService\x12\x44\n\x04\x43hat\x12\x1d.aiagents.chat.v1.ChatRequest\x1a\x1b.aiagents.chat.v1.ChatEvent0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.routes.pb.chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHATMESSAGE']._serialized_start=46
  _globals['_CHATMESSAGE']._serialized_end=90
  _globals['_CHATREQUEST']._serialized_start=92
  _globals['_CHATREQUEST']._serialized_end=154
  _globals['_CITATION']._serialized_start=156
  _globals['_CITATION']._serialized_end=211
  _globals['_DONE']._serialized_start=213
  _globals['_DONE']._serialized_end=219
  _globals['_CHATEVENT']._serialized_start=222
  _globals['_CHATEVENT']._serialized_end=363
  _globals['_CHATSERVICE']._serialized_start=365
  _globals['_CHATSERVICE']._serialized_end=448
# @@protoc_insertion_point(module_scope)
