# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.routes.pb import chat_pb2 as app_dot_routes_dot_pb_dot_chat__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in app/routes/pb/chat_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ChatServiceStub:
    """ChatService — recruiting-assistant chat. Server-streaming preserves the live
    token UX the SSE endpoint had: token deltas stream as `text`, then `citation`s,
    then `done`. A mid-stream LLM failure arrives as an `error` event (the stream
    still ends cleanly); auth/validation failures abort before the stream starts.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Chat = channel.unary_stream(
                '/aiagents.chat.v1.ChatService/Chat',
                request_serializer=app_dot_routes_dot_pb_dot_chat__pb2.ChatRequest.SerializeToString,
                response_deserializer=app_dot_routes_dot_pb_dot_chat__pb2.ChatEvent.FromString,
                _registered_method=True)


class ChatServiceServicer:
    """ChatService — recruiting-assistant chat. Server-streaming preserves the live
    token UX the SSE endpoint had: token deltas stream as `text`, then `citation`s,
    then `done`. A mid-stream LLM failure arrives as an `error` event (the stream
    still ends cleanly); auth/validation failures abort before the stream starts.
    """

    def Chat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Chat': grpc.unary_stream_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=app_dot_routes_dot_pb_dot_chat__pb2.ChatRequest.FromString,
                    response_serializer=app_dot_routes_dot_pb_dot_chat__pb2.ChatEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aiagents.chat.v1.ChatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aiagents.chat.v1.ChatService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChatService:
    """ChatService — recruiting-assistant chat. Server-streaming preserves the live
    token UX the SSE endpoint had: token deltas stream as `text`, then `citation`s,
    then `done`. A mid-stream LLM failure arrives as an `error` event (the stream
    still ends cleanly); auth/validation failures abort before the stream starts.
    """

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/aiagents.chat.v1.ChatService/Chat',
            app_dot_routes_dot_pb_dot_chat__pb2.ChatRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_chat__pb2.ChatEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
