# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.routes.pb import interview_pb2 as app_dot_routes_dot_pb_dot_interview__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in app/routes/pb/interview_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InterviewServiceStub:
    """InterviewService — candidate-facing live interview turns + proctoring + RTC token.
    Routes are thin: each RPC authenticates the caller from access-token metadata and
    calls an app/resources function (ownership/state checks live in the resource).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartInterview = channel.unary_unary(
                '/aiagents.interview.v1.InterviewService/StartInterview',
                request_serializer=app_dot_routes_dot_pb_dot_interview__pb2.StartInterviewRequest.SerializeToString,
                response_deserializer=app_dot_routes_dot_pb_dot_interview__pb2.QuestionResponse.FromString,
                _registered_method=True)
        self.SubmitTurn = channel.unary_unary(
                '/aiagents.interview.v1.InterviewService/SubmitTurn',
                request_serializer=app_dot_routes_dot_pb_dot_interview__pb2.SubmitTurnRequest.SerializeToString,
                response_deserializer=app_dot_routes_dot_pb_dot_interview__pb2.TurnResponse.FromString,
                _registered_method=True)
        self.RecordProctorEvents = channel.unary_unary(
                '/aiagents.interview.v1.InterviewService/RecordProctorEvents',
                request_serializer=app_dot_routes_dot_pb_dot_interview__pb2.ProctorEventsRequest.SerializeToString,
                response_deserializer=app_dot_routes_dot_pb_dot_interview__pb2.ProctorAccepted.FromString,
                _registered_method=True)
        self.RtcToken = channel.unary_unary(
                '/aiagents.interview.v1.InterviewService/RtcToken',
                request_serializer=app_dot_routes_dot_pb_dot_interview__pb2.RtcTokenRequest.SerializeToString,
                response_deserializer=app_dot_routes_dot_pb_dot_interview__pb2.RtcTokenResponse.FromString,
                _registered_method=True)


class InterviewServiceServicer:
    """InterviewService — candidate-facing live interview turns + proctoring + RTC token.
    Routes are thin: each RPC authenticates the caller from access-token metadata and
    calls an app/resources function (ownership/state checks live in the resource).
    """

    def StartInterview(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitTurn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordProctorEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RtcToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InterviewServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartInterview': grpc.unary_unary_rpc_method_handler(
                    servicer.StartInterview,
                    request_deserializer=app_dot_routes_dot_pb_dot_interview__pb2.StartInterviewRequest.FromString,
                    response_serializer=app_dot_routes_dot_pb_dot_interview__pb2.QuestionResponse.SerializeToString,
            ),
            'SubmitTurn': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitTurn,
                    request_deserializer=app_dot_routes_dot_pb_dot_interview__pb2.SubmitTurnRequest.FromString,
                    response_serializer=app_dot_routes_dot_pb_dot_interview__pb2.TurnResponse.SerializeToString,
            ),
            'RecordProctorEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordProctorEvents,
                    request_deserializer=app_dot_routes_dot_pb_dot_interview__pb2.ProctorEventsRequest.FromString,
                    response_serializer=app_dot_routes_dot_pb_dot_interview__pb2.ProctorAccepted.SerializeToString,
            ),
            'RtcToken': grpc.unary_unary_rpc_method_handler(
                    servicer.RtcToken,
                    request_deserializer=app_dot_routes_dot_pb_dot_interview__pb2.RtcTokenRequest.FromString,
                    response_serializer=app_dot_routes_dot_pb_dot_interview__pb2.RtcTokenResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aiagents.interview.v1.InterviewService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aiagents.interview.v1.InterviewService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InterviewService:
    """InterviewService — candidate-facing live interview turns + proctoring + RTC token.
    Routes are thin: each RPC authenticates the caller from access-token metadata and
    calls an app/resources function (ownership/state checks live in the resource).
    """

    @staticmethod
    def StartInterview(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aiagents.interview.v1.InterviewService/StartInterview',
            app_dot_routes_dot_pb_dot_interview__pb2.StartInterviewRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_interview__pb2.QuestionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitTurn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aiagents.interview.v1.InterviewService/SubmitTurn',
            app_dot_routes_dot_pb_dot_interview__pb2.SubmitTurnRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_interview__pb2.TurnResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordProctorEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aiagents.interview.v1.InterviewService/RecordProctorEvents',
            app_dot_routes_dot_pb_dot_interview__pb2.ProctorEventsRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_interview__pb2.ProctorAccepted.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RtcToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aiagents.interview.v1.InterviewService/RtcToken',
            app_dot_routes_dot_pb_dot_interview__pb2.RtcTokenRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_interview__pb2.RtcTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
