# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/routes/pb/jd.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'app/routes/pb/jd.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x61pp/routes/pb/jd.proto\x12\x0e\x61iagents.jd.v1\"!\n\x10ImproveJdRequest\x12\r\n\x05\x62rief\x18\x01 \x01(\t\"2\n\nJdResponse\x12\x0f\n\x07jd_text\x18\x01 \x01(\t\x12\x13\n\x0bsuggestions\x18\x02 \x03(\t2V\n\tJdService\x12I\n\tImproveJd\x12 .aiagents.jd.v1.ImproveJdRequest\x1a\x1a.aiagents.jd.v1.JdResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.routes.pb.jd_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMPROVEJDREQUEST']._serialized_start=42
  _globals['_IMPROVEJDREQUEST']._serialized_end=75
  _globals['_JDRESPONSE']._serialized_start=77
  _globals['_JDRESPONSE']._serialized_end=127
  _globals['_JDSERVICE']._serialized_start=129
  _globals['_JDSERVICE']._serialized_end=215
# @@protoc_insertion_point(module_scope)
