# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/routes/pb/practice.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'app/routes/pb/practice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x61pp/routes/pb/practice.proto\x12\x14\x61iagents.practice.v1\"6\n\x14StartPracticeRequest\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0f\n\x07jd_text\x18\x02 \x01(\t\"9\n\x10QuestionResponse\x12\x13\n\x0bpractice_id\x18\x01 \x01(\t\x12\x10\n\x08question\x18\x02 \x01(\t\"@\n\x19SubmitPracticeTurnRequest\x12\x13\n\x0bpractice_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61nswer\x18\x02 \x01(\t\".\n\x0cTurnResponse\x12\x0c\n\x04\x64one\x18\x01 \x01(\x08\x12\x10\n\x08question\x18\x02 \x01(\t\"\x1d\n\x1bListPracticeSessionsRequest\"N\n\x0fPracticeSession\x12\x13\n\x0bpractice_id\x18\x01 \x01(\t\x12\x12\n\nrole_label\x18\x02 \x01(\t\x12\x12\n\ncreated_at\x18\x03 \x01(\t\"N\n\x13PracticeSessionList\x12\x37\n\x08sessions\x18\x01 \x03(\x0b\x32%.aiagents.practice.v1.PracticeSession\"1\n\x1aGetPracticeFeedbackRequest\x12\x13\n\x0bpractice_id\x18\x01 \x01(\t\"\\\n\x0eGrowthFeedback\x12\x0f\n\x07summary\x18\x01 \x01(\t\x12\x11\n\tstrengths\x18\x02 \x03(\t\x12\x0c\n\x04gaps\x18\x03 \x03(\t\x12\x18\n\x10suggested_topics\x18\x04 \x03(\t\"f\n\x10PracticeFeedback\x12\x1a\n\x12\x65valuation_summary\x18\x01 \x01(\t\x12\x36\n\x08\x66\x65\x65\x64\x62\x61\x63k\x18\x02 \x01(\x0b\x32$.aiagents.practice.v1.GrowthFeedback2\xc8\x03\n\x0fPracticeService\x12\x63\n\rStartPractice\x12*.aiagents.practice.v1.StartPracticeRequest\x1a&.aiagents.practice.v1.QuestionResponse\x12i\n\x12SubmitPracticeTurn\x12/.aiagents.practice.v1.SubmitPracticeTurnRequest\x1a\".aiagents.practice.v1.TurnResponse\x12t\n\x14ListPracticeSessions\x12\x31.aiagents.practice.v1.ListPracticeSessionsRequest\x1a).aiagents.practice.v1.PracticeSessionList\x12o\n\x13GetPracticeFeedback\x12\x30.aiagents.practice.v1.GetPracticeFeedbackRequest\x1a&.aiagents.practice.v1.PracticeFeedbackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.routes.pb.practice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STARTPRACTICEREQUEST']._serialized_start=54
  _globals['_STARTPRACTICEREQUEST']._serialized_end=108
  _globals['_QUESTIONRESPONSE']._serialized_start=110
  _globals['_QUESTIONRESPONSE']._serialized_end=167
  _globals['_SUBMITPRACTICETURNREQUEST']._serialized_start=169
  _globals['_SUBMITPRACTICETURNREQUEST']._serialized_end=233
  _globals['_TURNRESPONSE']._serialized_start=235
  _globals['_TURNRESPONSE']._serialized_end=281
  _globals['_LISTPRACTICESESSIONSREQUEST']._serialized_start=283
  _globals['_LISTPRACTICESESSIONSREQUEST']._serialized_end=312
  _globals['_PRACTICESESSION']._serialized_start=314
  _globals['_PRACTICESESSION']._serialized_end=392
  _globals['_PRACTICESESSIONLIST']._serialized_start=394
  _globals['_PRACTICESESSIONLIST']._serialized_end=472
  _globals['_GETPRACTICEFEEDBACKREQUEST']._serialized_start=474
  _globals['_GETPRACTICEFEEDBACKREQUEST']._serialized_end=523
  _globals['_GROWTHFEEDBACK']._serialized_start=525
  _globals['_GROWTHFEEDBACK']._serialized_end=617
  _globals['_PRACTICEFEEDBACK']._serialized_start=619
  _globals['_PRACTICEFEEDBACK']._serialized_end=721
  _globals['_PRACTICESERVICE']._serialized_start=724
  _globals['_PRACTICESERVICE']._serialized_end=1180
# @@protoc_insertion_point(module_scope)
