# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/pb/aptitude.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'app/pb/aptitude.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x61pp/pb/aptitude.proto\x12\x11\x61\x64min.aptitude.v1\"(\n\x0eGetTestRequest\x12\x16\n\x0e\x61pplication_id\x18\x01 \x01(\t\"S\n\x10\x41ptitudeQuestion\x12\r\n\x05index\x18\x01 \x01(\x05\x12\x10\n\x08question\x18\x02 \x01(\t\x12\x0f\n\x07options\x18\x03 \x03(\t\x12\r\n\x05topic\x18\x04 \x01(\t\"^\n\x0c\x41ptitudeTest\x12\x16\n\x0e\x61pplication_id\x18\x01 \x01(\t\x12\x36\n\tquestions\x18\x02 \x03(\x0b\x32#.admin.aptitude.v1.AptitudeQuestion\"8\n\rSubmitRequest\x12\x16\n\x0e\x61pplication_id\x18\x01 \x01(\t\x12\x0f\n\x07\x61nswers\x18\x02 \x03(\x05\"G\n\x0e\x41ptitudeResult\x12\x16\n\x0e\x61pplication_id\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x05\x12\x0e\n\x06passed\x18\x03 \x01(\x08\x32\xbf\x01\n\x0f\x41ptitudeService\x12U\n\x0fGetAptitudeTest\x12!.admin.aptitude.v1.GetTestRequest\x1a\x1f.admin.aptitude.v1.AptitudeTest\x12U\n\x0eSubmitAptitude\x12 .admin.aptitude.v1.SubmitRequest\x1a!.admin.aptitude.v1.AptitudeResultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.routes.pb.aptitude_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETTESTREQUEST']._serialized_start=44
  _globals['_GETTESTREQUEST']._serialized_end=84
  _globals['_APTITUDEQUESTION']._serialized_start=86
  _globals['_APTITUDEQUESTION']._serialized_end=169
  _globals['_APTITUDETEST']._serialized_start=171
  _globals['_APTITUDETEST']._serialized_end=265
  _globals['_SUBMITREQUEST']._serialized_start=267
  _globals['_SUBMITREQUEST']._serialized_end=323
  _globals['_APTITUDERESULT']._serialized_start=325
  _globals['_APTITUDERESULT']._serialized_end=396
  _globals['_APTITUDESERVICE']._serialized_start=399
  _globals['_APTITUDESERVICE']._serialized_end=590
# @@protoc_insertion_point(module_scope)
