# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/routes/pb/compliance.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'app/routes/pb/compliance.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x61pp/routes/pb/compliance.proto\x12\x13\x61\x64min.compliance.v1\"<\n\x14RecordConsentRequest\x12\r\n\x05scope\x18\x01 \x01(\t\x12\x15\n\rterms_version\x18\x02 \x01(\t\"\x15\n\x13GetMyConsentRequest\"G\n\x0e\x43onsentReceipt\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05scope\x18\x02 \x01(\t\x12\x15\n\rterms_version\x18\x03 \x01(\t\"G\n\x0b\x43onsentItem\x12\r\n\x05scope\x18\x01 \x01(\t\x12\x15\n\rterms_version\x18\x02 \x01(\t\x12\x12\n\ngranted_at\x18\x03 \x01(\t\">\n\x0b\x43onsentList\x12/\n\x05items\x18\x01 \x03(\x0b\x32 .admin.compliance.v1.ConsentItem\"\x10\n\x0e\x45raseMeRequest\"/\n\x0c\x45raseReceipt\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0e\n\x06\x65rased\x18\x02 \x01(\x08\x32\xa3\x02\n\x11\x43omplianceService\x12_\n\rRecordConsent\x12).admin.compliance.v1.RecordConsentRequest\x1a#.admin.compliance.v1.ConsentReceipt\x12Z\n\x0cGetMyConsent\x12(.admin.compliance.v1.GetMyConsentRequest\x1a .admin.compliance.v1.ConsentList\x12Q\n\x07\x45raseMe\x12#.admin.compliance.v1.EraseMeRequest\x1a!.admin.compliance.v1.EraseReceiptb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.routes.pb.compliance_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RECORDCONSENTREQUEST']._serialized_start=55
  _globals['_RECORDCONSENTREQUEST']._serialized_end=115
  _globals['_GETMYCONSENTREQUEST']._serialized_start=117
  _globals['_GETMYCONSENTREQUEST']._serialized_end=138
  _globals['_CONSENTRECEIPT']._serialized_start=140
  _globals['_CONSENTRECEIPT']._serialized_end=211
  _globals['_CONSENTITEM']._serialized_start=213
  _globals['_CONSENTITEM']._serialized_end=284
  _globals['_CONSENTLIST']._serialized_start=286
  _globals['_CONSENTLIST']._serialized_end=348
  _globals['_ERASEMEREQUEST']._serialized_start=350
  _globals['_ERASEMEREQUEST']._serialized_end=366
  _globals['_ERASERECEIPT']._serialized_start=368
  _globals['_ERASERECEIPT']._serialized_end=415
  _globals['_COMPLIANCESERVICE']._serialized_start=418
  _globals['_COMPLIANCESERVICE']._serialized_end=709
# @@protoc_insertion_point(module_scope)
