# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.routes.pb import compliance_pb2 as app_dot_routes_dot_pb_dot_compliance__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in app/routes/pb/compliance_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ComplianceServiceStub:
    """ComplianceService — candidate data-rights, self-service (caller acts on their own data).
    Consent ledger now; right-to-erasure (RTBF) added next.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RecordConsent = channel.unary_unary(
                '/admin.compliance.v1.ComplianceService/RecordConsent',
                request_serializer=app_dot_routes_dot_pb_dot_compliance__pb2.RecordConsentRequest.SerializeToString,
                response_deserializer=app_dot_routes_dot_pb_dot_compliance__pb2.ConsentReceipt.FromString,
                _registered_method=True)
        self.GetMyConsent = channel.unary_unary(
                '/admin.compliance.v1.ComplianceService/GetMyConsent',
                request_serializer=app_dot_routes_dot_pb_dot_compliance__pb2.GetMyConsentRequest.SerializeToString,
                response_deserializer=app_dot_routes_dot_pb_dot_compliance__pb2.ConsentList.FromString,
                _registered_method=True)
        self.EraseMe = channel.unary_unary(
                '/admin.compliance.v1.ComplianceService/EraseMe',
                request_serializer=app_dot_routes_dot_pb_dot_compliance__pb2.EraseMeRequest.SerializeToString,
                response_deserializer=app_dot_routes_dot_pb_dot_compliance__pb2.EraseReceipt.FromString,
                _registered_method=True)


class ComplianceServiceServicer:
    """ComplianceService — candidate data-rights, self-service (caller acts on their own data).
    Consent ledger now; right-to-erasure (RTBF) added next.
    """

    def RecordConsent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMyConsent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EraseMe(self, request, context):
        """right-to-erasure (self)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ComplianceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RecordConsent': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordConsent,
                    request_deserializer=app_dot_routes_dot_pb_dot_compliance__pb2.RecordConsentRequest.FromString,
                    response_serializer=app_dot_routes_dot_pb_dot_compliance__pb2.ConsentReceipt.SerializeToString,
            ),
            'GetMyConsent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMyConsent,
                    request_deserializer=app_dot_routes_dot_pb_dot_compliance__pb2.GetMyConsentRequest.FromString,
                    response_serializer=app_dot_routes_dot_pb_dot_compliance__pb2.ConsentList.SerializeToString,
            ),
            'EraseMe': grpc.unary_unary_rpc_method_handler(
                    servicer.EraseMe,
                    request_deserializer=app_dot_routes_dot_pb_dot_compliance__pb2.EraseMeRequest.FromString,
                    response_serializer=app_dot_routes_dot_pb_dot_compliance__pb2.EraseReceipt.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'admin.compliance.v1.ComplianceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('admin.compliance.v1.ComplianceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ComplianceService:
    """ComplianceService — candidate data-rights, self-service (caller acts on their own data).
    Consent ledger now; right-to-erasure (RTBF) added next.
    """

    @staticmethod
    def RecordConsent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.compliance.v1.ComplianceService/RecordConsent',
            app_dot_routes_dot_pb_dot_compliance__pb2.RecordConsentRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_compliance__pb2.ConsentReceipt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMyConsent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.compliance.v1.ComplianceService/GetMyConsent',
            app_dot_routes_dot_pb_dot_compliance__pb2.GetMyConsentRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_compliance__pb2.ConsentList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EraseMe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.compliance.v1.ComplianceService/EraseMe',
            app_dot_routes_dot_pb_dot_compliance__pb2.EraseMeRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_compliance__pb2.EraseReceipt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
