# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/routes/pb/decision.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'app/routes/pb/decision.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x61pp/routes/pb/decision.proto\x12\x11\x61\x64min.decision.v1\"8\n\rDecideRequest\x12\x16\n\x0e\x61pplication_id\x18\x01 \x01(\t\x12\x0f\n\x07outcome\x18\x02 \x01(\t\"-\n\x13OverrideGateRequest\x12\x16\n\x0e\x61pplication_id\x18\x01 \x01(\t\"9\n\x10\x44\x65\x63isionResponse\x12\x16\n\x0e\x61pplication_id\x18\x01 \x01(\t\x12\r\n\x05state\x18\x02 \x01(\t\"X\n\x16HoldApplicationRequest\x12\x16\n\x0e\x61pplication_id\x18\x01 \x01(\t\x12\x13\n\x0breason_code\x18\x02 \x01(\t\x12\x11\n\tfree_text\x18\x03 \x01(\t\"[\n\x17HoldApplicationResponse\x12\x16\n\x0e\x61pplication_id\x18\x01 \x01(\t\x12\x11\n\tnew_state\x18\x02 \x01(\t\x12\x15\n\raudited_at_ms\x18\x03 \x01(\x03\"Z\n\x18RejectApplicationRequest\x12\x16\n\x0e\x61pplication_id\x18\x01 \x01(\t\x12\x13\n\x0breason_code\x18\x02 \x01(\t\x12\x11\n\tfree_text\x18\x03 \x01(\t\"]\n\x19RejectApplicationResponse\x12\x16\n\x0e\x61pplication_id\x18\x01 \x01(\t\x12\x11\n\tnew_state\x18\x02 \x01(\t\x12\x15\n\raudited_at_ms\x18\x03 \x01(\x03\x32\xa4\x03\n\x0f\x44\x65\x63isionService\x12Z\n\x11\x44\x65\x63ideApplication\x12 .admin.decision.v1.DecideRequest\x1a#.admin.decision.v1.DecisionResponse\x12[\n\x0cOverrideGate\x12&.admin.decision.v1.OverrideGateRequest\x1a#.admin.decision.v1.DecisionResponse\x12h\n\x0fHoldApplication\x12).admin.decision.v1.HoldApplicationRequest\x1a*.admin.decision.v1.HoldApplicationResponse\x12n\n\x11RejectApplication\x12+.admin.decision.v1.RejectApplicationRequest\x1a,.admin.decision.v1.RejectApplicationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.routes.pb.decision_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DECIDEREQUEST']._serialized_start=51
  _globals['_DECIDEREQUEST']._serialized_end=107
  _globals['_OVERRIDEGATEREQUEST']._serialized_start=109
  _globals['_OVERRIDEGATEREQUEST']._serialized_end=154
  _globals['_DECISIONRESPONSE']._serialized_start=156
  _globals['_DECISIONRESPONSE']._serialized_end=213
  _globals['_HOLDAPPLICATIONREQUEST']._serialized_start=215
  _globals['_HOLDAPPLICATIONREQUEST']._serialized_end=303
  _globals['_HOLDAPPLICATIONRESPONSE']._serialized_start=305
  _globals['_HOLDAPPLICATIONRESPONSE']._serialized_end=396
  _globals['_REJECTAPPLICATIONREQUEST']._serialized_start=398
  _globals['_REJECTAPPLICATIONREQUEST']._serialized_end=488
  _globals['_REJECTAPPLICATIONRESPONSE']._serialized_start=490
  _globals['_REJECTAPPLICATIONRESPONSE']._serialized_end=583
  _globals['_DECISIONSERVICE']._serialized_start=586
  _globals['_DECISIONSERVICE']._serialized_end=1006
# @@protoc_insertion_point(module_scope)
