# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.routes.pb import job_pb2 as app_dot_routes_dot_pb_dot_job__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in app/routes/pb/job_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class JobServiceStub:
    """JobService — company-side job posting + lifecycle. Auth via `authorization`
    metadata; jobs are scoped to the caller's company (comp_id from the token).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateJob = channel.unary_unary(
                '/admin.job.v1.JobService/CreateJob',
                request_serializer=app_dot_routes_dot_pb_dot_job__pb2.CreateJobRequest.SerializeToString,
                response_deserializer=app_dot_routes_dot_pb_dot_job__pb2.JobResponse.FromString,
                _registered_method=True)
        self.UpdateJob = channel.unary_unary(
                '/admin.job.v1.JobService/UpdateJob',
                request_serializer=app_dot_routes_dot_pb_dot_job__pb2.UpdateJobRequest.SerializeToString,
                response_deserializer=app_dot_routes_dot_pb_dot_job__pb2.JobResponse.FromString,
                _registered_method=True)
        self.GetJob = channel.unary_unary(
                '/admin.job.v1.JobService/GetJob',
                request_serializer=app_dot_routes_dot_pb_dot_job__pb2.GetJobRequest.SerializeToString,
                response_deserializer=app_dot_routes_dot_pb_dot_job__pb2.JobResponse.FromString,
                _registered_method=True)
        self.ListJobs = channel.unary_unary(
                '/admin.job.v1.JobService/ListJobs',
                request_serializer=app_dot_routes_dot_pb_dot_job__pb2.ListJobsRequest.SerializeToString,
                response_deserializer=app_dot_routes_dot_pb_dot_job__pb2.ListJobsResponse.FromString,
                _registered_method=True)
        self.PublishJob = channel.unary_unary(
                '/admin.job.v1.JobService/PublishJob',
                request_serializer=app_dot_routes_dot_pb_dot_job__pb2.PublishJobRequest.SerializeToString,
                response_deserializer=app_dot_routes_dot_pb_dot_job__pb2.JobResponse.FromString,
                _registered_method=True)
        self.GetPublicJob = channel.unary_unary(
                '/admin.job.v1.JobService/GetPublicJob',
                request_serializer=app_dot_routes_dot_pb_dot_job__pb2.GetJobRequest.SerializeToString,
                response_deserializer=app_dot_routes_dot_pb_dot_job__pb2.PublicJob.FromString,
                _registered_method=True)


class JobServiceServicer:
    """JobService — company-side job posting + lifecycle. Auth via `authorization`
    metadata; jobs are scoped to the caller's company (comp_id from the token).
    """

    def CreateJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListJobs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPublicJob(self, request, context):
        """Public read of a PUBLISHED job (any authenticated user) — title + JD only.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JobServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateJob,
                    request_deserializer=app_dot_routes_dot_pb_dot_job__pb2.CreateJobRequest.FromString,
                    response_serializer=app_dot_routes_dot_pb_dot_job__pb2.JobResponse.SerializeToString,
            ),
            'UpdateJob': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateJob,
                    request_deserializer=app_dot_routes_dot_pb_dot_job__pb2.UpdateJobRequest.FromString,
                    response_serializer=app_dot_routes_dot_pb_dot_job__pb2.JobResponse.SerializeToString,
            ),
            'GetJob': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJob,
                    request_deserializer=app_dot_routes_dot_pb_dot_job__pb2.GetJobRequest.FromString,
                    response_serializer=app_dot_routes_dot_pb_dot_job__pb2.JobResponse.SerializeToString,
            ),
            'ListJobs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListJobs,
                    request_deserializer=app_dot_routes_dot_pb_dot_job__pb2.ListJobsRequest.FromString,
                    response_serializer=app_dot_routes_dot_pb_dot_job__pb2.ListJobsResponse.SerializeToString,
            ),
            'PublishJob': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishJob,
                    request_deserializer=app_dot_routes_dot_pb_dot_job__pb2.PublishJobRequest.FromString,
                    response_serializer=app_dot_routes_dot_pb_dot_job__pb2.JobResponse.SerializeToString,
            ),
            'GetPublicJob': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPublicJob,
                    request_deserializer=app_dot_routes_dot_pb_dot_job__pb2.GetJobRequest.FromString,
                    response_serializer=app_dot_routes_dot_pb_dot_job__pb2.PublicJob.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'admin.job.v1.JobService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('admin.job.v1.JobService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class JobService:
    """JobService — company-side job posting + lifecycle. Auth via `authorization`
    metadata; jobs are scoped to the caller's company (comp_id from the token).
    """

    @staticmethod
    def CreateJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.job.v1.JobService/CreateJob',
            app_dot_routes_dot_pb_dot_job__pb2.CreateJobRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_job__pb2.JobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.job.v1.JobService/UpdateJob',
            app_dot_routes_dot_pb_dot_job__pb2.UpdateJobRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_job__pb2.JobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.job.v1.JobService/GetJob',
            app_dot_routes_dot_pb_dot_job__pb2.GetJobRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_job__pb2.JobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListJobs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.job.v1.JobService/ListJobs',
            app_dot_routes_dot_pb_dot_job__pb2.ListJobsRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_job__pb2.ListJobsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.job.v1.JobService/PublishJob',
            app_dot_routes_dot_pb_dot_job__pb2.PublishJobRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_job__pb2.JobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPublicJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.job.v1.JobService/GetPublicJob',
            app_dot_routes_dot_pb_dot_job__pb2.GetJobRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_job__pb2.PublicJob.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
