# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/routes/pb/preferences.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'app/routes/pb/preferences.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x61pp/routes/pb/preferences.proto\x12\x14\x61\x64min.preferences.v1\"\x16\n\x14GetAppearanceRequest\"L\n\nAppearance\x12\x0c\n\x04mode\x18\x01 \x01(\t\x12\x0c\n\x04\x62\x61se\x18\x02 \x01(\t\x12\x0e\n\x06\x61\x63\x63\x65nt\x18\x03 \x01(\t\x12\x12\n\naccent_hue\x18\x04 \x01(\r2\xcb\x01\n\x12PreferencesService\x12]\n\rGetAppearance\x12*.admin.preferences.v1.GetAppearanceRequest\x1a .admin.preferences.v1.Appearance\x12V\n\x10UpdateAppearance\x12 .admin.preferences.v1.Appearance\x1a .admin.preferences.v1.Appearanceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.routes.pb.preferences_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETAPPEARANCEREQUEST']._serialized_start=57
  _globals['_GETAPPEARANCEREQUEST']._serialized_end=79
  _globals['_APPEARANCE']._serialized_start=81
  _globals['_APPEARANCE']._serialized_end=157
  _globals['_PREFERENCESSERVICE']._serialized_start=160
  _globals['_PREFERENCESSERVICE']._serialized_end=363
# @@protoc_insertion_point(module_scope)
