# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

from app.routes.pb import (
    recommendation_pb2 as app_dot_routes_dot_pb_dot_recommendation__pb2,
)

GRPC_GENERATED_VERSION = "1.81.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in app/routes/pb/recommendation_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class RecommendationServiceStub:
    """RecommendationService — candidates see their own job matches; recruiters see a job's
    ranked applicants. Reads the match_results the AI Matcher (ai-agents) writes;
    comp_id-scoped via the job (the tenant source of truth).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCandidateRecommendations = channel.unary_unary(
            "/admin.recommendation.v1.RecommendationService/GetCandidateRecommendations",
            request_serializer=app_dot_routes_dot_pb_dot_recommendation__pb2.CandidateRecommendationsRequest.SerializeToString,
            response_deserializer=app_dot_routes_dot_pb_dot_recommendation__pb2.MatchList.FromString,
            _registered_method=True,
        )
        self.GetJobRankedCandidates = channel.unary_unary(
            "/admin.recommendation.v1.RecommendationService/GetJobRankedCandidates",
            request_serializer=app_dot_routes_dot_pb_dot_recommendation__pb2.JobRankedRequest.SerializeToString,
            response_deserializer=app_dot_routes_dot_pb_dot_recommendation__pb2.MatchList.FromString,
            _registered_method=True,
        )


class RecommendationServiceServicer:
    """RecommendationService — candidates see their own job matches; recruiters see a job's
    ranked applicants. Reads the match_results the AI Matcher (ai-agents) writes;
    comp_id-scoped via the job (the tenant source of truth).
    """

    def GetCandidateRecommendations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetJobRankedCandidates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_RecommendationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetCandidateRecommendations": grpc.unary_unary_rpc_method_handler(
            servicer.GetCandidateRecommendations,
            request_deserializer=app_dot_routes_dot_pb_dot_recommendation__pb2.CandidateRecommendationsRequest.FromString,
            response_serializer=app_dot_routes_dot_pb_dot_recommendation__pb2.MatchList.SerializeToString,
        ),
        "GetJobRankedCandidates": grpc.unary_unary_rpc_method_handler(
            servicer.GetJobRankedCandidates,
            request_deserializer=app_dot_routes_dot_pb_dot_recommendation__pb2.JobRankedRequest.FromString,
            response_serializer=app_dot_routes_dot_pb_dot_recommendation__pb2.MatchList.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "admin.recommendation.v1.RecommendationService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "admin.recommendation.v1.RecommendationService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class RecommendationService:
    """RecommendationService — candidates see their own job matches; recruiters see a job's
    ranked applicants. Reads the match_results the AI Matcher (ai-agents) writes;
    comp_id-scoped via the job (the tenant source of truth).
    """

    @staticmethod
    def GetCandidateRecommendations(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/admin.recommendation.v1.RecommendationService/GetCandidateRecommendations",
            app_dot_routes_dot_pb_dot_recommendation__pb2.CandidateRecommendationsRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_recommendation__pb2.MatchList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetJobRankedCandidates(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/admin.recommendation.v1.RecommendationService/GetJobRankedCandidates",
            app_dot_routes_dot_pb_dot_recommendation__pb2.JobRankedRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_recommendation__pb2.MatchList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
