# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.routes.pb import rubric_pb2 as app_dot_routes_dot_pb_dot_rubric__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in app/routes/pb/rubric_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RubricServiceStub:
    """RubricService — recruiters manage reusable interview rubrics (named competency sets)
    for their company. Comp-scoped CRUD; a rubric can later seed an interview blueprint.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateRubric = channel.unary_unary(
                '/admin.rubric.v1.RubricService/CreateRubric',
                request_serializer=app_dot_routes_dot_pb_dot_rubric__pb2.CreateRubricRequest.SerializeToString,
                response_deserializer=app_dot_routes_dot_pb_dot_rubric__pb2.Rubric.FromString,
                _registered_method=True)
        self.ListRubrics = channel.unary_unary(
                '/admin.rubric.v1.RubricService/ListRubrics',
                request_serializer=app_dot_routes_dot_pb_dot_rubric__pb2.ListRubricsRequest.SerializeToString,
                response_deserializer=app_dot_routes_dot_pb_dot_rubric__pb2.RubricList.FromString,
                _registered_method=True)
        self.UpdateRubric = channel.unary_unary(
                '/admin.rubric.v1.RubricService/UpdateRubric',
                request_serializer=app_dot_routes_dot_pb_dot_rubric__pb2.UpdateRubricRequest.SerializeToString,
                response_deserializer=app_dot_routes_dot_pb_dot_rubric__pb2.Rubric.FromString,
                _registered_method=True)
        self.DeleteRubric = channel.unary_unary(
                '/admin.rubric.v1.RubricService/DeleteRubric',
                request_serializer=app_dot_routes_dot_pb_dot_rubric__pb2.DeleteRubricRequest.SerializeToString,
                response_deserializer=app_dot_routes_dot_pb_dot_rubric__pb2.DeleteRubricResponse.FromString,
                _registered_method=True)


class RubricServiceServicer:
    """RubricService — recruiters manage reusable interview rubrics (named competency sets)
    for their company. Comp-scoped CRUD; a rubric can later seed an interview blueprint.
    """

    def CreateRubric(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRubrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateRubric(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteRubric(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RubricServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateRubric': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRubric,
                    request_deserializer=app_dot_routes_dot_pb_dot_rubric__pb2.CreateRubricRequest.FromString,
                    response_serializer=app_dot_routes_dot_pb_dot_rubric__pb2.Rubric.SerializeToString,
            ),
            'ListRubrics': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRubrics,
                    request_deserializer=app_dot_routes_dot_pb_dot_rubric__pb2.ListRubricsRequest.FromString,
                    response_serializer=app_dot_routes_dot_pb_dot_rubric__pb2.RubricList.SerializeToString,
            ),
            'UpdateRubric': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateRubric,
                    request_deserializer=app_dot_routes_dot_pb_dot_rubric__pb2.UpdateRubricRequest.FromString,
                    response_serializer=app_dot_routes_dot_pb_dot_rubric__pb2.Rubric.SerializeToString,
            ),
            'DeleteRubric': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteRubric,
                    request_deserializer=app_dot_routes_dot_pb_dot_rubric__pb2.DeleteRubricRequest.FromString,
                    response_serializer=app_dot_routes_dot_pb_dot_rubric__pb2.DeleteRubricResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'admin.rubric.v1.RubricService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('admin.rubric.v1.RubricService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RubricService:
    """RubricService — recruiters manage reusable interview rubrics (named competency sets)
    for their company. Comp-scoped CRUD; a rubric can later seed an interview blueprint.
    """

    @staticmethod
    def CreateRubric(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.rubric.v1.RubricService/CreateRubric',
            app_dot_routes_dot_pb_dot_rubric__pb2.CreateRubricRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_rubric__pb2.Rubric.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRubrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.rubric.v1.RubricService/ListRubrics',
            app_dot_routes_dot_pb_dot_rubric__pb2.ListRubricsRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_rubric__pb2.RubricList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateRubric(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.rubric.v1.RubricService/UpdateRubric',
            app_dot_routes_dot_pb_dot_rubric__pb2.UpdateRubricRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_rubric__pb2.Rubric.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteRubric(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.rubric.v1.RubricService/DeleteRubric',
            app_dot_routes_dot_pb_dot_rubric__pb2.DeleteRubricRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_rubric__pb2.DeleteRubricResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
