# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/routes/pb/saved_jobs.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'app/routes/pb/saved_jobs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x61pp/routes/pb/saved_jobs.proto\x12\x13\x61\x64min.saved_jobs.v1\" \n\x0eSaveJobRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\" \n\x0fSaveJobResponse\x12\r\n\x05saved\x18\x01 \x01(\x08\"\"\n\x10UnsaveJobRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\"\"\n\x11UnsaveJobResponse\x12\r\n\x05saved\x18\x01 \x01(\x08\"\x16\n\x14ListSavedJobsRequest\"\x9a\x02\n\x08SavedJob\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x14\n\x0c\x63ompany_name\x18\x03 \x01(\t\x12\x12\n\ncompany_id\x18\x04 \x01(\t\x12\x10\n\x08location\x18\x05 \x01(\t\x12\x13\n\x0bremote_mode\x18\x06 \x01(\t\x12\x17\n\x0f\x65mployment_type\x18\x07 \x01(\t\x12\x12\n\nsalary_min\x18\x08 \x01(\x03\x12\x12\n\nsalary_max\x18\t \x01(\x03\x12\x17\n\x0fsalary_currency\x18\n \x01(\t\x12\x0e\n\x06skills\x18\x0b \x03(\t\x12\x11\n\tposted_at\x18\x0c \x01(\t\x12\x0f\n\x07snippet\x18\r \x01(\t\x12\x10\n\x08saved_at\x18\x0e \x01(\t\"D\n\x15ListSavedJobsResponse\x12+\n\x04jobs\x18\x01 \x03(\x0b\x32\x1d.admin.saved_jobs.v1.SavedJob2\xac\x02\n\x10SavedJobsService\x12T\n\x07SaveJob\x12#.admin.saved_jobs.v1.SaveJobRequest\x1a$.admin.saved_jobs.v1.SaveJobResponse\x12Z\n\tUnsaveJob\x12%.admin.saved_jobs.v1.UnsaveJobRequest\x1a&.admin.saved_jobs.v1.UnsaveJobResponse\x12\x66\n\rListSavedJobs\x12).admin.saved_jobs.v1.ListSavedJobsRequest\x1a*.admin.saved_jobs.v1.ListSavedJobsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.routes.pb.saved_jobs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SAVEJOBREQUEST']._serialized_start=55
  _globals['_SAVEJOBREQUEST']._serialized_end=87
  _globals['_SAVEJOBRESPONSE']._serialized_start=89
  _globals['_SAVEJOBRESPONSE']._serialized_end=121
  _globals['_UNSAVEJOBREQUEST']._serialized_start=123
  _globals['_UNSAVEJOBREQUEST']._serialized_end=157
  _globals['_UNSAVEJOBRESPONSE']._serialized_start=159
  _globals['_UNSAVEJOBRESPONSE']._serialized_end=193
  _globals['_LISTSAVEDJOBSREQUEST']._serialized_start=195
  _globals['_LISTSAVEDJOBSREQUEST']._serialized_end=217
  _globals['_SAVEDJOB']._serialized_start=220
  _globals['_SAVEDJOB']._serialized_end=502
  _globals['_LISTSAVEDJOBSRESPONSE']._serialized_start=504
  _globals['_LISTSAVEDJOBSRESPONSE']._serialized_end=572
  _globals['_SAVEDJOBSSERVICE']._serialized_start=575
  _globals['_SAVEDJOBSSERVICE']._serialized_end=875
# @@protoc_insertion_point(module_scope)
