# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.routes.pb import scheduling_pb2 as app_dot_routes_dot_pb_dot_scheduling__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in app/routes/pb/scheduling_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SchedulingServiceStub:
    """SchedulingService — coordinate the live human interview after the AI screen passes.
    Funnel-adjacent: its own status + version CAS, never writes funnel state. All datetimes
    are ISO-8601 UTC strings on the wire.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProposeSlots = channel.unary_unary(
                '/admin.scheduling.v1.SchedulingService/ProposeSlots',
                request_serializer=app_dot_routes_dot_pb_dot_scheduling__pb2.ProposeSlotsRequest.SerializeToString,
                response_deserializer=app_dot_routes_dot_pb_dot_scheduling__pb2.ScheduleDTO.FromString,
                _registered_method=True)
        self.Reschedule = channel.unary_unary(
                '/admin.scheduling.v1.SchedulingService/Reschedule',
                request_serializer=app_dot_routes_dot_pb_dot_scheduling__pb2.ProposeSlotsRequest.SerializeToString,
                response_deserializer=app_dot_routes_dot_pb_dot_scheduling__pb2.ScheduleDTO.FromString,
                _registered_method=True)
        self.GetSchedule = channel.unary_unary(
                '/admin.scheduling.v1.SchedulingService/GetSchedule',
                request_serializer=app_dot_routes_dot_pb_dot_scheduling__pb2.GetScheduleRequest.SerializeToString,
                response_deserializer=app_dot_routes_dot_pb_dot_scheduling__pb2.ScheduleDTO.FromString,
                _registered_method=True)
        self.ChooseSlot = channel.unary_unary(
                '/admin.scheduling.v1.SchedulingService/ChooseSlot',
                request_serializer=app_dot_routes_dot_pb_dot_scheduling__pb2.ChooseSlotRequest.SerializeToString,
                response_deserializer=app_dot_routes_dot_pb_dot_scheduling__pb2.ScheduleDTO.FromString,
                _registered_method=True)
        self.Cancel = channel.unary_unary(
                '/admin.scheduling.v1.SchedulingService/Cancel',
                request_serializer=app_dot_routes_dot_pb_dot_scheduling__pb2.CancelRequest.SerializeToString,
                response_deserializer=app_dot_routes_dot_pb_dot_scheduling__pb2.ScheduleDTO.FromString,
                _registered_method=True)
        self.GetIcs = channel.unary_unary(
                '/admin.scheduling.v1.SchedulingService/GetIcs',
                request_serializer=app_dot_routes_dot_pb_dot_scheduling__pb2.GetIcsRequest.SerializeToString,
                response_deserializer=app_dot_routes_dot_pb_dot_scheduling__pb2.IcsResponse.FromString,
                _registered_method=True)
        self.ListCandidateInterviews = channel.unary_unary(
                '/admin.scheduling.v1.SchedulingService/ListCandidateInterviews',
                request_serializer=app_dot_routes_dot_pb_dot_scheduling__pb2.ListCandidateRequest.SerializeToString,
                response_deserializer=app_dot_routes_dot_pb_dot_scheduling__pb2.BookingListResponse.FromString,
                _registered_method=True)
        self.ListCompanyBookings = channel.unary_unary(
                '/admin.scheduling.v1.SchedulingService/ListCompanyBookings',
                request_serializer=app_dot_routes_dot_pb_dot_scheduling__pb2.ListCompanyRequest.SerializeToString,
                response_deserializer=app_dot_routes_dot_pb_dot_scheduling__pb2.BookingListResponse.FromString,
                _registered_method=True)


class SchedulingServiceServicer:
    """SchedulingService — coordinate the live human interview after the AI screen passes.
    Funnel-adjacent: its own status + version CAS, never writes funnel state. All datetimes
    are ISO-8601 UTC strings on the wire.
    """

    def ProposeSlots(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reschedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSchedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChooseSlot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Cancel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIcs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCandidateInterviews(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCompanyBookings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SchedulingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProposeSlots': grpc.unary_unary_rpc_method_handler(
                    servicer.ProposeSlots,
                    request_deserializer=app_dot_routes_dot_pb_dot_scheduling__pb2.ProposeSlotsRequest.FromString,
                    response_serializer=app_dot_routes_dot_pb_dot_scheduling__pb2.ScheduleDTO.SerializeToString,
            ),
            'Reschedule': grpc.unary_unary_rpc_method_handler(
                    servicer.Reschedule,
                    request_deserializer=app_dot_routes_dot_pb_dot_scheduling__pb2.ProposeSlotsRequest.FromString,
                    response_serializer=app_dot_routes_dot_pb_dot_scheduling__pb2.ScheduleDTO.SerializeToString,
            ),
            'GetSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSchedule,
                    request_deserializer=app_dot_routes_dot_pb_dot_scheduling__pb2.GetScheduleRequest.FromString,
                    response_serializer=app_dot_routes_dot_pb_dot_scheduling__pb2.ScheduleDTO.SerializeToString,
            ),
            'ChooseSlot': grpc.unary_unary_rpc_method_handler(
                    servicer.ChooseSlot,
                    request_deserializer=app_dot_routes_dot_pb_dot_scheduling__pb2.ChooseSlotRequest.FromString,
                    response_serializer=app_dot_routes_dot_pb_dot_scheduling__pb2.ScheduleDTO.SerializeToString,
            ),
            'Cancel': grpc.unary_unary_rpc_method_handler(
                    servicer.Cancel,
                    request_deserializer=app_dot_routes_dot_pb_dot_scheduling__pb2.CancelRequest.FromString,
                    response_serializer=app_dot_routes_dot_pb_dot_scheduling__pb2.ScheduleDTO.SerializeToString,
            ),
            'GetIcs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIcs,
                    request_deserializer=app_dot_routes_dot_pb_dot_scheduling__pb2.GetIcsRequest.FromString,
                    response_serializer=app_dot_routes_dot_pb_dot_scheduling__pb2.IcsResponse.SerializeToString,
            ),
            'ListCandidateInterviews': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCandidateInterviews,
                    request_deserializer=app_dot_routes_dot_pb_dot_scheduling__pb2.ListCandidateRequest.FromString,
                    response_serializer=app_dot_routes_dot_pb_dot_scheduling__pb2.BookingListResponse.SerializeToString,
            ),
            'ListCompanyBookings': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCompanyBookings,
                    request_deserializer=app_dot_routes_dot_pb_dot_scheduling__pb2.ListCompanyRequest.FromString,
                    response_serializer=app_dot_routes_dot_pb_dot_scheduling__pb2.BookingListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'admin.scheduling.v1.SchedulingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('admin.scheduling.v1.SchedulingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SchedulingService:
    """SchedulingService — coordinate the live human interview after the AI screen passes.
    Funnel-adjacent: its own status + version CAS, never writes funnel state. All datetimes
    are ISO-8601 UTC strings on the wire.
    """

    @staticmethod
    def ProposeSlots(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.scheduling.v1.SchedulingService/ProposeSlots',
            app_dot_routes_dot_pb_dot_scheduling__pb2.ProposeSlotsRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_scheduling__pb2.ScheduleDTO.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reschedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.scheduling.v1.SchedulingService/Reschedule',
            app_dot_routes_dot_pb_dot_scheduling__pb2.ProposeSlotsRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_scheduling__pb2.ScheduleDTO.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.scheduling.v1.SchedulingService/GetSchedule',
            app_dot_routes_dot_pb_dot_scheduling__pb2.GetScheduleRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_scheduling__pb2.ScheduleDTO.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChooseSlot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.scheduling.v1.SchedulingService/ChooseSlot',
            app_dot_routes_dot_pb_dot_scheduling__pb2.ChooseSlotRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_scheduling__pb2.ScheduleDTO.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Cancel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.scheduling.v1.SchedulingService/Cancel',
            app_dot_routes_dot_pb_dot_scheduling__pb2.CancelRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_scheduling__pb2.ScheduleDTO.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetIcs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.scheduling.v1.SchedulingService/GetIcs',
            app_dot_routes_dot_pb_dot_scheduling__pb2.GetIcsRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_scheduling__pb2.IcsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCandidateInterviews(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.scheduling.v1.SchedulingService/ListCandidateInterviews',
            app_dot_routes_dot_pb_dot_scheduling__pb2.ListCandidateRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_scheduling__pb2.BookingListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCompanyBookings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/admin.scheduling.v1.SchedulingService/ListCompanyBookings',
            app_dot_routes_dot_pb_dot_scheduling__pb2.ListCompanyRequest.SerializeToString,
            app_dot_routes_dot_pb_dot_scheduling__pb2.BookingListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
