# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/routes/pb/sourcing.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'app/routes/pb/sourcing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x61pp/routes/pb/sourcing.proto\x12\x11\x61\x64min.sourcing.v1\"k\n\x17SearchCandidatesRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\r\n\x05stage\x18\x02 \x01(\t\x12\x11\n\tmin_score\x18\x03 \x01(\x01\x12\x0c\n\x04page\x18\x04 \x01(\x05\x12\x11\n\tpage_size\x18\x05 \x01(\x05\"\x82\x01\n\x0c\x43\x61ndidateHit\x12\x19\n\x11\x63\x61ndidate_user_id\x18\x01 \x01(\t\x12\x19\n\x11\x61pplication_count\x18\x02 \x01(\x03\x12\x11\n\tfit_score\x18\x03 \x01(\x01\x12\x11\n\ttop_stage\x18\x04 \x01(\t\x12\x16\n\x0ematched_skills\x18\x05 \x03(\t\"y\n\x18SearchCandidatesResponse\x12-\n\x04hits\x18\x01 \x03(\x0b\x32\x1f.admin.sourcing.v1.CandidateHit\x12\r\n\x05total\x18\x02 \x01(\x05\x12\x0c\n\x04page\x18\x03 \x01(\x05\x12\x11\n\tpage_size\x18\x04 \x01(\x05\x32~\n\x0fSourcingService\x12k\n\x10SearchCandidates\x12*.admin.sourcing.v1.SearchCandidatesRequest\x1a+.admin.sourcing.v1.SearchCandidatesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.routes.pb.sourcing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SEARCHCANDIDATESREQUEST']._serialized_start=51
  _globals['_SEARCHCANDIDATESREQUEST']._serialized_end=158
  _globals['_CANDIDATEHIT']._serialized_start=161
  _globals['_CANDIDATEHIT']._serialized_end=291
  _globals['_SEARCHCANDIDATESRESPONSE']._serialized_start=293
  _globals['_SEARCHCANDIDATESRESPONSE']._serialized_end=414
  _globals['_SOURCINGSERVICE']._serialized_start=416
  _globals['_SOURCINGSERVICE']._serialized_end=542
# @@protoc_insertion_point(module_scope)
